#!/bin/bash
# app_amd_ws installer - AMD via WebSocket for Asterisk (ViciDial dialers)
#
# Generated by tools/gen-installer.sh from commit 2ef54b1 on 2026-09-22 (installer version 2ef54b1). DO NOT EDIT: run 'make installer'.
#
# One-liner (as root):   curl -fsSL <url>/install.sh | bash
# Usage:                 bash install.sh [options]      (bash install.sh --help)
#
# Self-contained: this file carries app_amd_ws.c, the Makefile, ast-detect.sh and
# amd_ws.conf.sample.  It never adds package repositories and never upgrades Asterisk.
# Everything it prints also goes to /var/log/app_amd_ws-install.log.
#
# Exit codes: 0 ok | 1 failure | 2 usage / not root | 3 installed but the OLD module is still
# loaded (in use; activation pending) | 4 no matching Asterisk headers | 5 build/load failed |
# 6 dependencies missing

set -euo pipefail
# NOTE: never 'cmd | grep -q' in a condition here - with pipefail the writer's SIGPIPE makes the
# pipeline fail although grep matched.  Use 'cmd | grep pattern >/dev/null' (reads all input).

AMD_WS_INSTALLER_VERSION='2ef54b1'
AMD_WS_SOURCE_COMMIT='2ef54b1'
MODULE=app_amd_ws
APP=AMD_WS

# ----------------------------------------------------------------------------------------------
# defaults / options
# ----------------------------------------------------------------------------------------------
OPT_UNINSTALL=0; OPT_DEPS_ONLY=0; OPT_BUILD_ONLY=0; OPT_NO_DB=0; OPT_NO_LOAD=0; OPT_DRY_RUN=0
OPT_YES=0; OPT_ALLOW_CONFIGURE=0; OPT_REMOVE_BACKUPS=0; OPT_KEEP_BUILD=0
OPT_HEADERS=''; OPT_ASTERISK_SRC=''; OPT_VERSION=''; OPT_TARBALL_FILE=''; OPT_OUTPUT=''
OPT_WAIT=30
BUNDLE_URL=${AMD_WS_BUNDLE_URL:-https://download.amdy.io/asterisk-headers}
CACHE_DIR=${AMD_WS_CACHE_DIR:-/var/cache/app_amd_ws}
LOG_FILE=${AMD_WS_LOG_FILE:-/var/log/app_amd_ws-install.log}
ETC_DIR=${AMD_WS_ETCDIR:-/etc/asterisk}
CURL_OPTS=(-fsSL --connect-timeout 15 --max-time 900)
BUILD_DIR=''
HEADERS_HOW=''

usage() {
    cat <<EOF
app_amd_ws installer $AMD_WS_INSTALLER_VERSION (module source commit $AMD_WS_SOURCE_COMMIT)

Usage: bash install.sh [options]

  (no option)         install dependencies, resolve Asterisk headers, build, install, load, verify
  --uninstall         unload and remove the module (+ header cache); keeps amd_ws.conf and packages
  --deps-only         only install the build dependencies
  --build-only        only build; write the module to --output (default ./app_amd_ws.so); no root needed
  --no-db             build without the ViciDial phone/country lookup (no MySQL client needed)
  --no-load           install the file but do not unload/load the module in the running Asterisk
  --headers DIR       use this Asterisk include dir (must hold asterisk.h, asterisk/autoconfig.h, buildopts.h)
  --asterisk-src DIR  use this configured+built Asterisk source tree (DIR/include)
  --version VER       Asterisk version to build for when it cannot be detected (e.g. 16.30.1-vici)
  --allow-configure   permit running ./configure in a downloaded source tree if no autoconfig.h is available
  --bundle-url URL    header bundle base URL (default: $BUNDLE_URL)
  --tarball-file F    use this local Asterisk source tarball instead of downloading one
  --wait N            seconds to wait for a busy module to become idle before giving up (default 30)
  --remove-backups    with --uninstall: also delete app_amd_ws.so.bak.* files
  --dry-run           detect and print the plan; change nothing (no root needed)
  --keep-build        keep the temporary build directory
  -y, --yes           no confirmation prompts
  -h, --help          this text

Environment overrides: ASTERISK ASTVERSION ASTBUILDSUM ASTINCDIR ASTTOPDIR ASTMODDIR AST_SRC_ROOTS
AST_INC_ROOTS ASTNOCHECK=1 AMD_WS_BUNDLE_URL AMD_WS_CACHE_DIR AMD_WS_LOG_FILE AMD_WS_ETCDIR MYSQL_CFLAGS MYSQL_LIBS

Exit codes: 0 ok, 1 failure, 2 usage/not root, 3 installed but old module still loaded (in use),
4 no matching headers, 5 build or load failed, 6 dependencies missing
EOF
}

# ----------------------------------------------------------------------------------------------
# logging: console (info -> stdout, warn/error -> stderr) AND the log file.  Functions never
# return values through stdout, so logging can never pollute a captured result.
# ----------------------------------------------------------------------------------------------
_ts() { date '+%Y-%m-%d %H:%M:%S'; }
_logfile() { { printf '%s %s\n' "$(_ts)" "$*" >> "$LOG_FILE"; } 2>/dev/null || true; }
log()  { printf '[amd_ws] %s\n' "$*"; _logfile "INFO  $*"; }
warn() { printf '[amd_ws] WARNING: %s\n' "$*" >&2; _logfile "WARN  $*"; }
err()  { printf '[amd_ws] ERROR: %s\n' "$*" >&2; _logfile "ERROR $*"; }
die()  { local rc=$1; shift; err "$@"; exit "$rc"; }
run_logged() {   # run a command, tee its output to the log; rc preserved (pipefail)
    _logfile "RUN   $*"
    "$@" 2>&1 | tee -a "$LOG_FILE"
}

init_log() {
    if ! { : >> "$LOG_FILE"; } 2>/dev/null; then
        LOG_FILE="${TMPDIR:-/tmp}/app_amd_ws-install.log"
        { : >> "$LOG_FILE"; } 2>/dev/null || LOG_FILE=/dev/null
    fi
    _logfile "===== install.sh $AMD_WS_INSTALLER_VERSION (commit $AMD_WS_SOURCE_COMMIT) args: $*"
}

# ----------------------------------------------------------------------------------------------
# traps: the EXIT trap must never turn a successful run into rc 1 (if-form, explicit return 0)
# ----------------------------------------------------------------------------------------------
on_exit() {
    local rc=$?
    if [ -n "$BUILD_DIR" ] && [ -d "$BUILD_DIR" ]; then
        if [ "$OPT_KEEP_BUILD" = 1 ]; then log "build directory kept: $BUILD_DIR"; else rm -rf "$BUILD_DIR"; fi
    fi
    _logfile "===== exit $rc"
    return 0
}
on_err() { err "command failed at line $1 (exit $2); see $LOG_FILE"; }

# ==============================================================================================
# embedded ast-detect.sh (identical to the repository file; also written into the build dir)
# ==============================================================================================
# ast-detect.sh - find the Asterisk that is RUNNING (else installed) on this box and a header
# tree that matches it.  Shared by the Makefile and by install.sh (embedded verbatim), so both
# always take the same decision.
#
# POSIX sh (tested with dash and bash).  Every diagnostic goes to STDERR, so callers can use
# $(...) safely; nothing but the requested output ever appears on stdout.
#
# Usage as a library:
#     . ./ast-detect.sh; ast_detect || exit 1
#     make ASTERISK="$ASTERISK" ASTVERSION="$ASTVERSION" ASTBUILDSUM="$ASTBUILDSUM" ASTINCDIR="$ASTINCDIR" ...
# Usage standalone:
#     sh ast-detect.sh            -> KEY=VALUE lines (shell syntax) on stdout, rc 0 = usable headers found
#     sh ast-detect.sh --make     -> KEY := VALUE lines (GNU make syntax) on stdout, rc 0 = usable headers found
#     sh ast-detect.sh --running  -> rc 0 if an Asterisk daemon answers 'core show version' within AST_TIMEOUT
#
# Overrides (environment, or on the make command line):
#     ASTERISK=/path/to/asterisk        the binary to fingerprint (default: the running daemon's image)
#     ASTERISK_OPTS='-C /etc/asterisk/asterisk.conf'   extra options for 'asterisk -rx' (auto: the daemon's -C)
#     ASTVERSION=16.30.1-vici           skip version detection
#     ASTBUILDSUM=<32 hex>              skip AST_BUILDOPT_SUM detection
#     ASTINCDIR=/path/include           use exactly this include dir (still validated unless ASTNOCHECK=1)
#     ASTTOPDIR=/path/asterisk-<ver>    use <ASTTOPDIR>/include (same rules)
#     ASTMODDIR=/path/modules           skip module-directory detection
#     AST_SRC_ROOTS="/usr/src ..."      where versioned source trees are searched
#     AST_INC_ROOTS="/usr/include ..."  where installed headers are searched
#     ASTNOCHECK=1                      downgrade a buildopt-sum mismatch / unverifiable headers to a WARNING
#     AST_TIMEOUT=5                     seconds allowed for every 'asterisk -rx' / 'asterisk -V' call
#
# Why all this: an out-of-tree module needs only headers, but they must belong to the same
# Asterisk version as the running core AND carry the same AST_BUILDOPT_SUM (main/loader.c refuses
# the module otherwise).  /usr/include, a distro -dev package and stray trees in /usr/src may all
# be from a different Asterisk than the one that is running, so every candidate is validated.

LC_ALL=C; export LC_ALL

AST_TIMEOUT=${AST_TIMEOUT:-5}
AST_SRC_ROOTS=${AST_SRC_ROOTS:-"/usr/src /usr/src/asterisk /usr/local/src /usr/local/src/asterisk"}
AST_INC_ROOTS=${AST_INC_ROOTS:-"/usr/include /usr/local/include"}
ASTNOCHECK=${ASTNOCHECK:-0}

ad_log()  { printf '[ast-detect] %s\n' "$*" >&2; }
ad_warn() { printf '[ast-detect] WARNING: %s\n' "$*" >&2; }
ad_err()  { printf '[ast-detect] ERROR: %s\n' "$*" >&2; }
ad_run()  { timeout "$AST_TIMEOUT" "$@" 2>/dev/null; }     # never hang on a broken/deadlocked binary

# ---------------------------------------------------------------------------------------------
# 1. binary: image of the running daemon (skipping 'asterisk -r' consoles) -> PATH -> well-known
# ---------------------------------------------------------------------------------------------
ast_daemon_pid() {
    # prints the PID of the daemon (not of a remote console), or nothing
    for p in $(pgrep -x asterisk 2>/dev/null); do
        tr '\0' ' ' < "/proc/$p/cmdline" 2>/dev/null | grep -- ' -r' >/dev/null && continue
        printf '%s\n' "$p"; return 0
    done
    return 1
}

# '-C <file>' of the daemon's command line, so that 'asterisk -rx' reaches a daemon started with a
# non-default asterisk.conf (its control socket lives wherever that file says)
ast_ctl_opts_of() { tr '\0' '\n' < "/proc/$1/cmdline" 2>/dev/null | awk '$0 == "-C" { getline f; printf "-C %s", f; exit }'; }

ast_find_binary() {
    ASTERISK_OPTS=${ASTERISK_OPTS:-}
    [ -n "${ASTERISK:-}" ] && { ASTERISK_SRC=override; return 0; }
    ASTERISK=''; ASTERISK_SRC=''
    p=$(ast_daemon_pid) || p=''
    if [ -n "$p" ]; then
        ASTERISK=$(readlink "/proc/$p/exe" 2>/dev/null | sed 's/ (deleted)$//')
        [ -n "$ASTERISK" ] && { ASTERISK_SRC="running process $p"; ASTERISK_OPTS=$(ast_ctl_opts_of "$p"); }
    fi
    [ -z "$ASTERISK" ] && { ASTERISK=$(command -v asterisk 2>/dev/null); ASTERISK_SRC=PATH; }
    if [ -z "$ASTERISK" ]; then
        for b in /usr/sbin/asterisk /usr/local/sbin/asterisk; do
            [ -x "$b" ] && { ASTERISK=$b; ASTERISK_SRC="well-known path"; break; }
        done
    fi
    [ -n "$ASTERISK" ] || ASTERISK_SRC="none found"
    [ -n "$ASTERISK" ]
}

# rc 0 when a daemon answers the CLI (the only reliable definition of "running")
ast_running() {
    [ -n "${ASTERISK:-}" ] || ast_find_binary || return 1
    # shellcheck disable=SC2086
    ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show version' | grep '^Asterisk ' >/dev/null
}

# ---------------------------------------------------------------------------------------------
# 2. version: 'core show version' -> 'asterisk -V' -> embedded string pair ("16.30.1-vici" + "163001")
# ---------------------------------------------------------------------------------------------
ast_version_filter() { sed -n 's/^Asterisk \([^ ][^ ]*\).*/\1/p' | head -n 1; }

# main/version.c stores the version string and its numeric form next to each other; requiring both
# avoids false hits like "10.0" from unrelated strings.
ast_version_from_strings() {
    strings -a "$1" 2>/dev/null | awk '
        /^[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)?(-[A-Za-z0-9.]+)?$/ || /^certified\/[0-9][0-9]*\.[0-9][0-9]*(-cert[0-9]+)?$/ { v[$0]=1 }
        /^[0-9][0-9][0-9][0-9][0-9][0-9]?$/ { n[$0]=1 }
        END { for (s in v) { t=s; sub(/^certified\//,"",t); sub(/-cert/,".",t); split(t,a,/[.-]/);
              if (sprintf("%d%02d%02d",a[1],a[2],a[3]) in n) print s } }' | sort -u | head -n 1
}

ast_find_version() {
    if [ -n "${ASTVERSION:-}" ]; then ASTVERSION_SRC=override
    else
        ASTVERSION=''; ASTVERSION_SRC=unknown
        if [ -n "${ASTERISK:-}" ]; then
            # shellcheck disable=SC2086
            ASTVERSION=$(ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show version' | ast_version_filter); ASTVERSION_SRC="running daemon (core show version)"
            if [ -z "$ASTVERSION" ]; then ASTVERSION=$(ad_run "$ASTERISK" -V | ast_version_filter); ASTVERSION_SRC="'$ASTERISK -V' (daemon not running; version on disk)"; fi
            if [ -z "$ASTVERSION" ]; then ASTVERSION=$(ast_version_from_strings "$ASTERISK"); ASTVERSION_SRC="strings(1) on $ASTERISK (binary does not run here)"; fi
            [ -n "$ASTVERSION" ] || ASTVERSION_SRC=unknown
            # binary on disk replaced after the daemon started?  Build for the RUNNING one, but say so.
            case $ASTVERSION_SRC in "running daemon"*)
                dv=$(ad_run "$ASTERISK" -V | ast_version_filter)
                [ -n "$dv" ] && [ "$dv" != "$ASTVERSION" ] && ad_warn "running Asterisk is $ASTVERSION but the binary on disk is $dv (restart pending?) - building for the RUNNING one";;
            esac
        fi
    fi
    # 16.30.1-vici -> 16.30.1 ; certified/18.9-cert1 -> 18.9 ; 18.10.0~dfsg... -> 18.10.0 ; GIT-... -> empty
    ASTVERBASE=$(printf '%s\n' "$ASTVERSION" | sed -n 's|^certified/||; s|^\([0-9][0-9]*\(\.[0-9][0-9]*\)\{1,2\}\).*|\1|p')
    ASTMAJOR=${ASTVERBASE%%.*}
    [ -n "$ASTVERSION" ]
}

# ---------------------------------------------------------------------------------------------
# 3. module dir: 'core show settings' -> asterisk.conf astmoddir -> first known dir holding pbx_config.so
# ---------------------------------------------------------------------------------------------
AST_MODDIR_CANDS="/usr/lib64/asterisk/modules /usr/lib/asterisk/modules /usr/lib/x86_64-linux-gnu/asterisk/modules /usr/local/lib/asterisk/modules /usr/local/lib64/asterisk/modules"

ast_find_moddir() {
    [ -n "${ASTMODDIR:-}" ] && { ASTMODDIR_SRC=override; return 0; }
    ASTMODDIR=''; ASTMODDIR_SRC=''
    if [ -n "${ASTERISK:-}" ]; then
        # shellcheck disable=SC2086
        ASTMODDIR=$(ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show settings' | sed -n 's/^ *Module directory: *//p' | head -n 1)
        [ -n "$ASTMODDIR" ] && ASTMODDIR_SRC="running daemon (core show settings)"
    fi
    if [ -z "$ASTMODDIR" ]; then
        ASTMODDIR=$(sed -n 's/^ *astmoddir *=> *\([^ ;]*\).*/\1/p' /etc/asterisk/asterisk.conf 2>/dev/null | head -n 1)
        [ -n "$ASTMODDIR" ] && ASTMODDIR_SRC="/etc/asterisk/asterisk.conf"
    fi
    if [ -z "$ASTMODDIR" ]; then
        for d in $AST_MODDIR_CANDS; do
            [ -f "$d/pbx_config.so" ] && { ASTMODDIR=$d; ASTMODDIR_SRC="contains pbx_config.so"; break; }
        done
    fi
    [ -n "$ASTMODDIR" ] || ASTMODDIR_SRC="not found"
    [ -n "$ASTMODDIR" ]
}

# ---------------------------------------------------------------------------------------------
# 4. AST_BUILDOPT_SUM of the core: the most frequent 32-hex string in the binary (one copy per
#    built-in module), else in a stock module.  NOT the 'Build Options' line of 'core show
#    settings' - that string also lists non-ABI flags (BUILD_NATIVE, ...) and is not the md5 input.
# ---------------------------------------------------------------------------------------------
ast_sum_of() { strings -a "$1" 2>/dev/null | grep -xE '[0-9a-f]{32}' | sort | uniq -c | sort -rn | awk 'NR==1{print $2}'; }

ast_find_buildsum() {
    [ -n "${ASTBUILDSUM:-}" ] && { ASTBUILDSUM_SRC=override; return 0; }
    ASTBUILDSUM=''; ASTBUILDSUM_SRC=''
    if [ -n "${ASTERISK:-}" ] && [ -r "$ASTERISK" ]; then
        ASTBUILDSUM=$(ast_sum_of "$ASTERISK"); ASTBUILDSUM_SRC="strings(1) on $ASTERISK"
    fi
    if [ -z "$ASTBUILDSUM" ] && [ -n "${ASTMODDIR:-}" ]; then
        for m in "$ASTMODDIR/pbx_config.so" "$ASTMODDIR/app_dial.so" "$ASTMODDIR/res_http_websocket.so"; do
            [ -f "$m" ] || continue
            ASTBUILDSUM=$(ast_sum_of "$m"); ASTBUILDSUM_SRC="strings(1) on $m"
            [ -n "$ASTBUILDSUM" ] && break
        done
    fi
    [ -n "$ASTBUILDSUM" ] || ASTBUILDSUM_SRC="unknown (no readable core binary or stock module)"
    [ -n "$ASTBUILDSUM" ]
}

# md5 of the ', '-joined ABI-relevant menuselect options + newline (build_tools/make_buildopts_h)
ast_sum_for_opts() { printf '%s\n' "$1" | md5sum | cut -c1-32; }

# Print the option list behind a known AST_BUILDOPT_SUM, or fail (rc 1) for an unknown sum.
# The candidates are the ABI-relevant options of menuselect (build_tools/cflags.xml order), in
# every combination, so any Asterisk >= 16 built from stock menuselect flags is covered.
# Asterisk 13 puts MALLOC_DEBUG/REF_DEBUG/LOW_MEMORY into the sum as well; 13 is out of scope.
ast_opts_for_sum() {
    _sum=$1
    case $_sum in
        da6642af068ee5e6490c5b1d2cc1d238) printf 'OPTIONAL_API\n'; return 0;;                  # stock 16/18/20/21/22 (ViciDial, ViciBox RPM)
        fa819827cbff2ea35341af5458859233) printf 'LOADABLE_MODULES, OPTIONAL_API\n'; return 0;; # stock 13
    esac
    # brute force over the ordered option set (2^9 = 512 md5 calls, about a second)
    _n=0
    while [ $_n -lt 512 ]; do
        _opts=''; _i=0
        for _o in DEBUG_THREADLOCALS DO_CRASH TEST_FRAMEWORK DEBUG_THREADS DEBUG_FD_LEAKS LOADABLE_MODULES OPTIONAL_API G711_NEW_ALGORITHM INTEGER_CALLERID; do
            if [ $(( (_n >> _i) & 1 )) -eq 1 ]; then
                _opts="${_opts:+$_opts, }$_o"
            fi
            _i=$((_i+1))
        done
        if [ -n "$_opts" ] && [ "$(ast_sum_for_opts "$_opts")" = "$_sum" ]; then printf '%s\n' "$_opts"; return 0; fi
        _n=$((_n+1))
    done
    return 1
}

# ast_synth_buildopts <include dir> <sum>: write <include dir>/asterisk/buildopts.h for a known sum.
# Used when only pristine headers are available (vendor header bundle, headers-only tarball extract).
ast_synth_buildopts() {
    _inc=$1; _sum=$2
    [ -n "$_sum" ] || { ad_err "cannot synthesise buildopts.h: AST_BUILDOPT_SUM of the running Asterisk is unknown"; return 1; }
    _opts=$(ast_opts_for_sum "$_sum") || { ad_err "AST_BUILDOPT_SUM $_sum is not one produced by stock menuselect options (custom build) - use the real configured+built source tree: ASTTOPDIR=/path/to/asterisk-<ver>"; return 1; }
    [ "$(ast_sum_for_opts "$_opts")" = "$_sum" ] || { ad_err "internal error: option list '$_opts' does not hash to $_sum"; return 1; }
    mkdir -p "$_inc/asterisk" || return 1
    {
        printf '/*\n * buildopts.h\n * Synthesised by ast-detect.sh for AST_BUILDOPT_SUM %s\n * (the running Asterisk was built with: %s)\n */\n\n' "$_sum" "$_opts"
        for _o in $(printf '%s' "$_opts" | tr -d ','); do printf '#define %s 1\n' "$_o"; done
        printf '#define AST_BUILDOPT_SUM "%s"\n' "$_sum"
        printf '#define AST_BUILDOPTS "%s"\n' "$_opts"
        printf '#define AST_BUILDOPTS_ALL "%s"\n' "$_opts"
    } > "$_inc/asterisk/buildopts.h" || return 1
    ad_log "synthesised $_inc/asterisk/buildopts.h (AST_BUILDOPTS \"$_opts\", sum $_sum)"
}

# ---------------------------------------------------------------------------------------------
# 5. validate one include dir.  rc 0 = usable; one '[ast-detect] accept/reject <dir>: <why>' line
#    on stderr.  Rules: asterisk.h + asterisk/autoconfig.h (configured) + asterisk/buildopts.h
#    (built or synthesised) must exist; the tree's .version must agree with the running version
#    when present; AST_BUILDOPT_SUM must equal the core's (mismatch = reject, ASTNOCHECK=1 = warn).
#    Installed headers without .version are tied to the binary by package version or by
#    install-time proximity (make install writes both within seconds); otherwise a WARNING.
# ---------------------------------------------------------------------------------------------
ast_check_incdir() {
    d=$1; why=''; note=''
    if   [ ! -f "$d/asterisk.h" ];            then why='no asterisk.h'
    elif [ ! -f "$d/asterisk/autoconfig.h" ]; then why='not configured (no asterisk/autoconfig.h)'
    elif [ ! -f "$d/asterisk/buildopts.h" ];  then why='not built (no asterisk/buildopts.h - ./configure alone is not enough)'
    else
        sum=$(sed -n 's/^#define AST_BUILDOPT_SUM "\([0-9a-f]*\)".*/\1/p' "$d/asterisk/buildopts.h" | head -n 1)
        # the candidate's OWN tree dir (not '$d/..', which would follow a symlinked include/ elsewhere)
        tv=$(sed -n 1p "${d%/include}/.version" 2>/dev/null)
        if [ -n "$tv" ] && [ -n "${ASTVERSION:-}" ] && [ "$tv" != "$ASTVERSION" ] && [ "$tv" != "$ASTVERBASE" ]; then
            why="tree version $tv != running $ASTVERSION"
        elif [ -n "${ASTBUILDSUM:-}" ] && [ "$sum" != "$ASTBUILDSUM" ]; then
            if [ "$ASTNOCHECK" = 1 ]; then note="WARNING: AST_BUILDOPT_SUM ${sum:-none} != core $ASTBUILDSUM, accepted because ASTNOCHECK=1"
            else why="AST_BUILDOPT_SUM ${sum:-none} != core $ASTBUILDSUM (Asterisk would refuse to load the module)"; fi
        elif [ -z "$tv" ]; then
            pv=''
            if command -v rpm >/dev/null 2>&1; then pv=$(rpm -qf --qf '%{VERSION}' "$d/asterisk.h" 2>/dev/null | grep -v 'not owned'); fi
            if [ -z "$pv" ] && command -v dpkg-query >/dev/null 2>&1; then
                pkg=$(dpkg -S "$d/asterisk.h" 2>/dev/null | sed 's/:.*//;q')
                [ -n "$pkg" ] && pv=$(dpkg-query -W -f '${Version}' "$pkg" 2>/dev/null)
            fi
            pv=$(printf '%s' "$pv" | sed 's/^[0-9]*://')
            bm=$(stat -c %Y "${ASTERISK:-/nonexistent}" 2>/dev/null || echo 0); hm=$(stat -c %Y "$d/asterisk/buildopts.h" 2>/dev/null || echo 0)
            delta=$(( bm - hm )); [ $delta -lt 0 ] && delta=$(( -delta ))
            if   [ -n "$pv" ] && [ -n "$ASTVERBASE" ] && [ "${pv#"$ASTVERBASE"}" != "$pv" ]; then note="installed headers owned by package version $pv (matches running $ASTVERSION)"
            elif [ -n "$pv" ] && [ -n "$ASTVERBASE" ] && [ $delta -gt 3600 ]; then
                if [ "$ASTNOCHECK" = 1 ]; then note="WARNING: installed headers belong to package version $pv, running $ASTVERSION; accepted because ASTNOCHECK=1"
                else why="installed headers belong to package version $pv, running $ASTVERSION (and not rewritten by the same make install)"; fi
            elif [ $delta -le 3600 ] && [ "$bm" -gt 0 ]; then note="installed headers written within ${delta}s of the binary (same make install); sum matches"
            elif [ -z "${ASTBUILDSUM:-}" ]; then note="WARNING: unversioned headers and core sum unknown - cannot verify they match the running Asterisk"
            else note="WARNING: unversioned installed headers (not from a package, not installed together with the binary); AST_BUILDOPT_SUM matches but the Asterisk major version cannot be verified - prefer ASTTOPDIR=<matching source tree>"; fi
        else note="tree .version $tv matches"; fi
    fi
    if [ -n "$why" ]; then ad_log "reject $d: $why"; return 1; fi
    ad_log "accept $d: ${note:-ok}"; return 0
}

# ---------------------------------------------------------------------------------------------
# 6. candidates in priority order; the first valid one wins.
#    ASTINCDIR / ASTTOPDIR override the list; then trees named asterisk-<exact version>, trees of
#    the same base version (asterisk-<base>, asterisk-<base>-*, asterisk-certified-<base>*) under
#    AST_SRC_ROOTS - only directories with include/asterisk.h, so *.tar.gz, sound dirs and
#    asterisk-perl-* never match - then <prefix>/include next to the binary, then AST_INC_ROOTS.
# ---------------------------------------------------------------------------------------------
ad_add() { case " $cands " in *" $1 "*) ;; *) cands="$cands $1";; esac; }

ast_find_incdir() {
    cands=''; ASTINCDIR_SRC=''
    if [ -n "${ASTINCDIR:-}" ]; then cands=$ASTINCDIR; ASTINCDIR_SRC="ASTINCDIR override"
    elif [ -n "${ASTTOPDIR:-}" ]; then cands="$ASTTOPDIR/include"; ASTINCDIR_SRC="ASTTOPDIR override"
    else
        if [ -n "${ASTVERSION:-}" ]; then
            for r in $AST_SRC_ROOTS; do t="$r/asterisk-$ASTVERSION"; [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"; done
            if [ -n "$ASTVERBASE" ]; then
                for r in $AST_SRC_ROOTS; do
                    for t in "$r/asterisk-$ASTVERBASE" "$r"/asterisk-"$ASTVERBASE"-* "$r"/asterisk-certified-"$ASTVERBASE"*; do
                        [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"
                    done
                done
            fi
        else
            for r in $AST_SRC_ROOTS; do
                for t in "$r"/asterisk-[0-9]* "$r"/asterisk-certified-*; do [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"; done
            done
        fi
        case ${ASTERISK:-} in */sbin/asterisk) p=${ASTERISK%/sbin/asterisk}; [ -f "$p/include/asterisk.h" ] && ad_add "$p/include";; esac
        for r in $AST_INC_ROOTS; do [ -f "$r/asterisk.h" ] && ad_add "$r"; done
        cands=${cands# }
    fi
    ok=''; n=0
    for d in $cands; do ast_check_incdir "$d" && { ok="$ok $d"; n=$((n+1)); }; done
    ok=${ok# }
    if [ -n "${ASTINCDIR:-}" ]; then
        [ $n -eq 1 ] || [ "$ASTNOCHECK" = 1 ] || { ad_err "ASTINCDIR=$ASTINCDIR failed validation (ASTNOCHECK=1 forces it)"; return 1; }
        return 0
    fi
    if [ -n "${ASTTOPDIR:-}" ]; then
        [ $n -eq 1 ] || [ "$ASTNOCHECK" = 1 ] || { ad_err "ASTTOPDIR=$ASTTOPDIR failed validation (ASTNOCHECK=1 forces it)"; return 1; }
        ASTINCDIR="$ASTTOPDIR/include"; return 0
    fi
    if [ -z "${ASTVERSION:-}" ]; then
        # unknown version: accept only an unambiguous candidate that is tied to the core by its sum
        if [ $n -eq 1 ] && [ -n "${ASTBUILDSUM:-}" ]; then
            ASTINCDIR=$ok; ASTINCDIR_SRC="only sum-matching candidate (version unknown)"
            ad_warn "Asterisk version unknown; using the only header dir whose AST_BUILDOPT_SUM matches the core: $ASTINCDIR (pass ASTVERSION=... to be sure)"; return 0
        fi
        if [ $n -ge 1 ] && [ "$ASTNOCHECK" = 1 ]; then
            ASTINCDIR=${ok%% *}; ASTINCDIR_SRC="first candidate (version unknown, ASTNOCHECK=1)"
            ad_warn "Asterisk version unknown and ASTNOCHECK=1: using $ASTINCDIR unverified"; return 0
        fi
        ad_err "Asterisk version could not be detected ($n header dir(s) validated: ${ok:-none}) - pass ASTVERSION=<version> or ASTTOPDIR=/path/to/configured+built source tree (ASTNOCHECK=1 forces the first candidate)"
        return 1
    fi
    ASTINCDIR=${ok%% *}; ASTINCDIR_SRC="first validated candidate"
    [ -n "$ASTINCDIR" ] && return 0
    ad_err "no configured+built Asterisk $ASTVERSION headers with AST_BUILDOPT_SUM ${ASTBUILDSUM:-?} found (candidates: ${cands:-none}; roots: $AST_SRC_ROOTS $AST_INC_ROOTS)"
    ast_hint_no_headers
    return 1
}

# next steps when nothing validates (kept in one place so Makefile and installer say the same)
ast_hint_no_headers() {
    v=${ASTVERSION:-<version>}
    case $v in
        *-vici)      tb="https://download.vicidial.com/required-apps/asterisk-$v.tar.gz"; tree="asterisk-$v";;
        certified/*) tb="https://downloads.asterisk.org/pub/telephony/certified-asterisk/releases/asterisk-certified-${v#certified/}.tar.gz"; tree="asterisk-certified-${v#certified/}";;
        *)           tb="https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTVERBASE:-$v}.tar.gz (or old-releases/)"; tree="asterisk-${ASTVERBASE:-$v}";;
    esac
    ad_err "fix one of: (a) run install.sh, which fetches a header bundle or the headers of $tb and synthesises buildopts.h;"
    ad_err "             (b) extract + ./configure + 'make include/asterisk/buildopts.h' that tarball and pass ASTTOPDIR=/path/to/$tree;"
    ad_err "             (c) install the asterisk-devel/asterisk-dev package of EXACTLY the running version (only when Asterisk itself is the distro package);"
    ad_err "             (d) ASTNOCHECK=1 to accept mismatching headers at your own risk (the loader may refuse the module)."
}

# ---------------------------------------------------------------------------------------------
# all-in-one: sets ASTERISK ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR (+ *_SRC)
# ---------------------------------------------------------------------------------------------
ast_detect_core() {
    ast_find_binary   || ad_warn "no asterisk binary found (pass ASTERISK=/path/to/asterisk)"
    ast_find_version  || ad_warn "cannot determine the Asterisk version${ASTERISK:+ from $ASTERISK}"
    ast_find_moddir   || ad_warn "no Asterisk module directory found (pass ASTMODDIR=/path)"
    ast_find_buildsum || ad_warn "cannot read AST_BUILDOPT_SUM from the core or its modules"
    ad_log "binary   : ${ASTERISK:-none}${ASTERISK_OPTS:+ $ASTERISK_OPTS} ($ASTERISK_SRC)"
    ad_log "version  : ${ASTVERSION:-unknown} (base ${ASTVERBASE:-?}, major ${ASTMAJOR:-?}) via $ASTVERSION_SRC"
    ad_log "buildsum : ${ASTBUILDSUM:-unknown} via $ASTBUILDSUM_SRC"
    ad_log "moddir   : ${ASTMODDIR:-unknown} ($ASTMODDIR_SRC)"
}

ast_detect() {
    ast_detect_core
    ast_find_incdir || return 1
    ad_log "headers  : $ASTINCDIR ($ASTINCDIR_SRC)"
    export ASTERISK ASTERISK_OPTS ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR
    return 0
}

AST_DETECT_VARS="ASTERISK ASTERISK_OPTS ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR ASTERISK_SRC ASTVERSION_SRC ASTBUILDSUM_SRC ASTMODDIR_SRC ASTINCDIR_SRC"

ast_print_vars() {   # $1 = sh | make
    for v in $AST_DETECT_VARS; do
        eval "val=\${$v:-}"
        case $1 in
            make) printf '%s := %s\n' "$v" "$val";;
            *)    printf "%s='%s'\n" "$v" "$(printf '%s' "$val" | sed "s/'/'\\\\''/g")";;
        esac
    done
}

# standalone use (not when sourced as a library)
case ${0##*/} in
    ast-detect.sh)
        case ${1:-} in
            --running) ast_running; exit $?;;
            --make)    ast_detect; rc=$?; printf 'AST_DETECT_RC := %s\n' "$rc"; ast_print_vars make; exit $rc;;
            --help|-h) sed -n '2,32p' "$0"; exit 0;;
            *)         ast_detect; rc=$?; ast_print_vars sh; exit $rc;;
        esac;;
esac
# ==============================================================================================
# end of embedded ast-detect.sh
# ==============================================================================================
# route the library's diagnostics into the log file as well
ad_log()  { printf '[ast-detect] %s\n' "$*" >&2; _logfile "DETECT $*"; }
ad_warn() { printf '[ast-detect] WARNING: %s\n' "$*" >&2; _logfile "DETECT WARNING: $*"; }
ad_err()  { printf '[ast-detect] ERROR: %s\n' "$*" >&2; _logfile "DETECT ERROR: $*"; }

# ----------------------------------------------------------------------------------------------
# distro / package manager
# ----------------------------------------------------------------------------------------------
PKG=''; DISTRO=''
detect_distro() {
    local id='' like=''
    if [ -r /etc/os-release ]; then
        id=$(sed -n 's/^ID="\{0,1\}\([^"]*\)"\{0,1\}/\1/p' /etc/os-release | head -n1)
        like=$(sed -n 's/^ID_LIKE="\{0,1\}\([^"]*\)"\{0,1\}/\1/p' /etc/os-release | head -n1)
        DISTRO=$(sed -n 's/^PRETTY_NAME="\{0,1\}\([^"]*\)"\{0,1\}/\1/p' /etc/os-release | head -n1)
    fi
    [ -n "$DISTRO" ] || DISTRO=$(uname -sr)
    if command -v zypper >/dev/null 2>&1 && case " $id $like " in *suse*|*sles*|*opensuse*) true;; *) false;; esac; then PKG=zypper
    elif command -v dnf >/dev/null 2>&1; then PKG=dnf
    elif command -v yum >/dev/null 2>&1; then PKG=yum
    elif command -v apt-get >/dev/null 2>&1; then PKG=apt
    elif command -v zypper >/dev/null 2>&1; then PKG=zypper
    else PKG=none; fi
}

# tools the build needs -> the package that provides them, per package manager
need_pkgs() {          # sets NEED_PKGS (array) from missing commands
    NEED_PKGS=()
    local c p
    for c in gcc make pkg-config strings tar curl; do
        command -v "$c" >/dev/null 2>&1 && continue
        case $c in
            gcc) p=gcc;; make) p=make;; tar) p=tar;; curl) p=curl;; strings) p=binutils;;
            pkg-config) case $PKG in dnf|yum) p=pkgconfig;; *) p=pkg-config;; esac;;
        esac
        NEED_PKGS+=("$p")
    done
}

have_mysql_dev() {
    [ -n "${MYSQL_CFLAGS:-}${MYSQL_LIBS:-}" ] && return 0
    local p
    for p in libmariadb mariadb mysqlclient; do pkg-config --exists "$p" 2>/dev/null && return 0; done
    mariadb_config --cflags >/dev/null 2>&1 && return 0
    mysql_config --cflags >/dev/null 2>&1 && return 0
    return 1
}

mysql_dev_candidates() {   # sets MYSQL_DEV_PKGS (array), most likely first
    case $PKG in
        zypper) MYSQL_DEV_PKGS=(libmariadb-devel mariadb-devel libmysqlclient-devel);;
        dnf|yum) MYSQL_DEV_PKGS=(mariadb-connector-c-devel mariadb-devel mysql-devel);;
        apt) MYSQL_DEV_PKGS=(libmariadb-dev default-libmysqlclient-dev libmysqlclient-dev libmariadbclient-dev);;
        *) MYSQL_DEV_PKGS=();;
    esac
}

pkg_install() {   # install the given packages; never touches repositories; rc from the manager
    [ $# -gt 0 ] || return 0
    log "installing packages: $*"
    case $PKG in
        zypper) run_logged zypper --non-interactive install --no-recommends "$@";;
        dnf)    run_logged dnf -y install "$@";;
        yum)    run_logged yum -y install "$@";;
        apt)    export DEBIAN_FRONTEND=noninteractive
                if [ ! -d /var/lib/apt/lists ] || [ -z "$(ls -A /var/lib/apt/lists 2>/dev/null | grep -v lock)" ]; then
                    run_logged apt-get update -qq || warn "apt-get update failed - trying to install from the existing package lists"
                fi
                run_logged apt-get install -y --no-install-recommends "$@";;
        *)      err "no supported package manager (zypper/dnf/yum/apt-get); install by hand: $*"; return 1;;
    esac
}

install_deps() {
    need_pkgs
    local rc=0
    if [ ${#NEED_PKGS[@]} -gt 0 ]; then
        pkg_install "${NEED_PKGS[@]}" || rc=1
        need_pkgs
        [ ${#NEED_PKGS[@]} -eq 0 ] || { err "still missing after install: ${NEED_PKGS[*]}"; rc=1; }
    else
        log "build tools present (gcc make pkg-config strings tar curl)"
    fi
    if [ "$OPT_NO_DB" = 1 ]; then
        log "--no-db: MySQL/MariaDB client development files not needed"
    elif have_mysql_dev; then
        log "MySQL/MariaDB client development files present"
    else
        mysql_dev_candidates
        local p ok=0
        for p in ${MYSQL_DEV_PKGS[@]+"${MYSQL_DEV_PKGS[@]}"}; do   # (empty-array safe on bash 4.2)
            if pkg_install "$p" && have_mysql_dev; then ok=1; break; fi
        done
        if [ $ok = 0 ]; then
            warn "no MySQL/MariaDB client development package could be installed (tried: ${MYSQL_DEV_PKGS[*]:-none}) - building WITHOUT the vicidial_auto_calls phone/country lookup (use --no-db to silence this)"
            OPT_NO_DB=1
        fi
    fi
    return $rc
}

# ----------------------------------------------------------------------------------------------
# header resolution.  Order: (1) local trees / installed headers validated by ast-detect;
# (2) the distro's -devel package, only when the RUNNING binary is that distro package and is
# unmodified, pinned to the exact installed version; (3) header bundle from BUNDLE_URL;
# (4) headers-only extraction of the upstream / ViciDial source tarball + synthesised buildopts.h.
# Result: ASTINCDIR (validated) and HEADERS_HOW.  rc 1 when everything failed.
# ----------------------------------------------------------------------------------------------
resolve_headers() {
    ASTINCDIR=${ASTINCDIR:-$OPT_HEADERS}
    [ -n "${ASTTOPDIR:-}" ] || ASTTOPDIR=$OPT_ASTERISK_SRC
    if ast_find_incdir; then HEADERS_HOW="local: $ASTINCDIR ($ASTINCDIR_SRC)"; return 0; fi
    [ -z "${ASTINCDIR:-}${ASTTOPDIR:-}" ] || return 1     # an explicit --headers/--asterisk-src that fails is final
    [ -n "${ASTVERSION:-}" ] || { err "cannot fetch headers without knowing the Asterisk version - pass --version <ver> (e.g. 16.30.1-vici) or --asterisk-src DIR"; return 1; }
    if [ "$OPT_DRY_RUN" = 1 ]; then
        HEADERS_HOW="none locally; would try: distro devel package (if Asterisk is the distro package), $(bundle_urls | tr '\n' ' '), then $(tarball_urls | tr '\n' ' ')"
        return 0
    fi
    if try_devel_package; then ASTINCDIR=''; if ast_find_incdir; then HEADERS_HOW="distro devel package: $ASTINCDIR"; return 0; fi; fi
    if fetch_header_bundle; then HEADERS_HOW="header bundle: $ASTINCDIR"; return 0; fi
    if fetch_tarball_headers; then HEADERS_HOW="source tarball headers + synthesised buildopts.h: $ASTINCDIR"; return 0; fi
    return 1
}

# (2) -devel package pinned to the running binary's package version
try_devel_package() {
    local bin=${ASTERISK:-} pkg='' evr='' ver=''
    [ -n "$bin" ] && [ -e "$bin" ] || return 1
    if command -v rpm >/dev/null 2>&1 && pkg=$(rpm -qf "$bin" 2>/dev/null) && [ -n "$pkg" ] && [ "${pkg#file }" = "$pkg" ]; then
        if rpm -Vf "$bin" 2>/dev/null | grep " $bin\$" >/dev/null; then
            log "$bin is owned by $pkg but was modified (source build over the package) - not using the distro devel package"; return 1
        fi
        evr=$(rpm -q --qf '%{VERSION}-%{RELEASE}' "$pkg")
        log "Asterisk is the distro package $pkg - installing asterisk-devel-$evr (exact same version, never an upgrade)"
        case $PKG in
            zypper) run_logged zypper --non-interactive install --no-recommends --oldpackage "asterisk-devel-$evr" || return 1;;
            dnf)    run_logged dnf -y install "asterisk-devel-$evr" || return 1;;
            yum)    run_logged yum -y install "asterisk-devel-$evr" || return 1;;
            *)      return 1;;
        esac
        return 0
    fi
    if command -v dpkg-query >/dev/null 2>&1 && pkg=$(dpkg -S "$bin" 2>/dev/null | sed 's/:.*//;q') && [ -n "$pkg" ]; then
        if dpkg --verify "$pkg" 2>/dev/null | grep " $bin\$" >/dev/null; then
            log "$bin belongs to $pkg but was modified (source build over the package) - not using asterisk-dev"; return 1
        fi
        ver=$(dpkg-query -W -f '${Version}' "$pkg" 2>/dev/null)
        log "Asterisk is the distro package $pkg $ver - installing asterisk-dev=$ver"
        export DEBIAN_FRONTEND=noninteractive
        run_logged apt-get install -y --no-install-recommends "asterisk-dev=$ver" || return 1
        return 0
    fi
    log "Asterisk binary is not owned by a distro package - skipping the devel-package route"
    return 1
}

# pure helpers (stdout = data, no logging): candidate URLs for the running version
bundle_urls() {
    local v
    printf '%s/asterisk-%s-headers.tar.gz\n' "$BUNDLE_URL" "$ASTVERSION"
    v=${ASTVERSION#certified/}
    [ -n "${ASTVERBASE:-}" ] && [ "$ASTVERBASE" != "$v" ] && printf '%s/asterisk-%s-headers.tar.gz\n' "$BUNDLE_URL" "$ASTVERBASE"
    return 0
}
tarball_urls() {
    local v=${1:-$ASTVERSION} base=${2:-${ASTVERBASE:-}}
    case $v in
        *-vici)      printf 'https://download.vicidial.com/required-apps/asterisk-%s.tar.gz\n' "$v";;
        certified/*) printf 'https://downloads.asterisk.org/pub/telephony/certified-asterisk/releases/asterisk-certified-%s.tar.gz\n' "${v#certified/}"
                     printf 'https://downloads.asterisk.org/pub/telephony/certified-asterisk/old-releases/asterisk-certified-%s.tar.gz\n' "${v#certified/}"; return 0;;
    esac
    [ -n "$base" ] || return 0
    printf 'https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-%s.tar.gz\n' "$base"
    printf 'https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-%s.tar.gz\n' "$base"
}

# download $1 to $2; verify against the sidecar checksum $3 (URL, optional, may 404) when present
fetch_verified() {
    local url=$1 out=$2 sumurl=${3:-} want have
    log "downloading $url"
    curl "${CURL_OPTS[@]}" -o "$out" "$url" || { rm -f "$out"; return 1; }
    if [ -n "$sumurl" ]; then
        if want=$(curl "${CURL_OPTS[@]}" "$sumurl" 2>/dev/null | awk 'NF{print $1; exit}') && [ -n "$want" ]; then
            have=$(sha256sum "$out" | cut -c1-64)
            [ "$have" = "$want" ] || { err "sha256 mismatch for $url (got $have, published $want)"; rm -f "$out"; return 1; }
            log "sha256 verified ($want)"
        else
            log "no checksum published at $sumurl - continuing unverified"
        fi
    fi
    return 0
}

# (3) header bundle: asterisk-<ver>-headers.tar.gz (+ .sha256) -> CACHE_DIR/asterisk-<ver>/include
fetch_header_bundle() {
    local url tmp dir name
    tmp=$(mktemp) || return 1
    while read -r url; do
        [ -n "$url" ] || continue
        fetch_verified "$url" "$tmp" "$url.sha256" || { log "no header bundle at $url"; continue; }
        name=${url##*/}; name=${name%-headers.tar.gz}
        dir="$CACHE_DIR/$name"
        rm -rf "$dir"; mkdir -p "$dir"
        if ! tar xzf "$tmp" -C "$dir" --strip-components=1; then err "cannot extract $url"; rm -rf "$dir"; continue; fi
        rm -f "$tmp"
        [ -f "$dir/include/asterisk.h" ] || { err "bundle $url has no include/asterisk.h"; rm -rf "$dir"; continue; }
        rm -f "$dir/include/asterisk/buildopts.h"
        ast_synth_buildopts "$dir/include" "${ASTBUILDSUM:-}" || { rm -rf "$dir"; return 1; }
        ASTINCDIR="$dir/include"
        if ast_check_incdir "$ASTINCDIR"; then return 0; fi
        ASTINCDIR=''; rm -rf "$dir"
    done < <(bundle_urls)
    rm -f "$tmp"
    return 1
}

# (4) source tarball, headers only: */include/asterisk.h, */include/asterisk/*.h, */.version
fetch_tarball_headers() {
    local tmp='' url got=0 dir ac
    dir="$CACHE_DIR/asterisk-$ASTVERSION"
    if [ -n "$OPT_TARBALL_FILE" ]; then
        [ -f "$OPT_TARBALL_FILE" ] || { err "--tarball-file $OPT_TARBALL_FILE: no such file"; return 1; }
        tmp=$OPT_TARBALL_FILE; got=1; log "using local tarball $tmp"
    else
        tmp=$(mktemp) || return 1
        while read -r url; do
            [ -n "$url" ] || continue
            case $url in *downloads.asterisk.org*) fetch_verified "$url" "$tmp" "${url%.tar.gz}.sha256" && { got=1; break; };;
                          *) fetch_verified "$url" "$tmp" '' && { log "(download.vicidial.com publishes no checksums)"; got=1; break; };;
            esac
            log "not available: $url"
        done < <(tarball_urls)
        [ $got = 1 ] || { rm -f "$tmp"; err "no source tarball found for Asterisk $ASTVERSION (tried: $(tarball_urls | tr '\n' ' '))"; return 1; }
    fi
    rm -rf "$dir"; mkdir -p "$dir"
    log "extracting headers only (include/ and .version) into $dir"
    if ! tar xzf "$tmp" -C "$dir" --strip-components=1 --wildcards '*/include/asterisk.h' '*/include/asterisk/*.h' '*/.version' 2>>"$LOG_FILE"; then
        [ -f "$dir/include/asterisk.h" ] || { err "tar could not extract include/ from the tarball"; rm -rf "$dir"; [ -n "$OPT_TARBALL_FILE" ] || rm -f "$tmp"; return 1; }
    fi
    rm -f "$dir/include/asterisk/buildopts.h" "$dir/include/asterisk/build.h"
    [ -f "$dir/.version" ] || printf '%s\n' "$ASTVERSION" > "$dir/.version"
    # autoconfig.h: the tarball's own (built-tree tarball) > a cached bundle of the same major > ./configure
    if [ -f "$dir/include/asterisk/autoconfig.h" ]; then
        log "using the autoconfig.h shipped inside the tarball"
    elif ac=$(ls "$CACHE_DIR"/asterisk-"${ASTMAJOR:-x}".*/include/asterisk/autoconfig.h 2>/dev/null | head -n1) && [ -n "$ac" ]; then
        log "using autoconfig.h from the cached header bundle $ac (same major version, same platform)"
        cp -p "$ac" "$dir/include/asterisk/autoconfig.h"
    elif [ "$OPT_ALLOW_CONFIGURE" = 1 ]; then
        run_configure "$tmp" "$dir" || { rm -rf "$dir"; [ -n "$OPT_TARBALL_FILE" ] || rm -f "$tmp"; return 1; }
    else
        err "the tarball carries no include/asterisk/autoconfig.h (it is generated by ./configure) and no header bundle for Asterisk ${ASTMAJOR:-?}.x is cached"
        err "options: re-run with --allow-configure (runs ./configure in $CACHE_DIR/src; needs gcc-c++, libedit/ncurses, libuuid, jansson >= 2.11, libxml2, sqlite3 -devel packages),"
        err "         or configure the tree yourself and pass --asterisk-src DIR, or pass --headers DIR"
        rm -rf "$dir"; [ -n "$OPT_TARBALL_FILE" ] || rm -f "$tmp"; return 1
    fi
    [ -n "$OPT_TARBALL_FILE" ] || rm -f "$tmp"
    ast_synth_buildopts "$dir/include" "${ASTBUILDSUM:-}" || { rm -rf "$dir"; return 1; }
    ASTINCDIR="$dir/include"
    ast_check_incdir "$ASTINCDIR" && return 0
    ASTINCDIR=''; return 1
}

run_configure() {   # $1 = tarball, $2 = header dir to receive autoconfig.h
    local tb=$1 dir=$2 src="$CACHE_DIR/src-$ASTVERSION"
    rm -rf "$src"; mkdir -p "$src"
    log "--allow-configure: extracting the full source into $src and running ./configure (this takes a minute)"
    tar xzf "$tb" -C "$src" --strip-components=1 || { err "full extraction failed"; return 1; }
    if ! ( cd "$src" && ./configure --quiet >"$src/configure.log" 2>&1 ); then
        err "./configure failed - last lines of $src/configure.log:"; tail -n 15 "$src/configure.log" >&2
        err "install the missing -devel packages named there and re-run, or pass --headers/--asterisk-src"
        return 1
    fi
    cp -p "$src/include/asterisk/autoconfig.h" "$dir/include/asterisk/autoconfig.h" || return 1
    log "autoconfig.h generated by ./configure"
}

# ----------------------------------------------------------------------------------------------
# build in a temporary directory with the embedded sources; the Makefile runs the gates
# ----------------------------------------------------------------------------------------------
write_sources() {
    local d=$1
    cat > "$d/app_amd_ws.c" <<'__APP_AMD_WS_EMBED_EOF__'
/* @@PLACEHOLDER app_amd_ws.c@@ - this installer was generated without the module source */
#error "app_amd_ws.c placeholder: regenerate install.sh with tools/gen-installer.sh in a checkout that contains app_amd_ws.c"
__APP_AMD_WS_EMBED_EOF__
    cat > "$d/Makefile" <<'__APP_AMD_WS_EMBED_EOF__'
# Makefile for app_amd_ws - AMD via WebSocket (res_http_websocket) module for Asterisk >= 16
#
#   make                 build app_amd_ws.so for the Asterisk that is running / installed on this box
#   make show-config     print what was detected (binary, version, buildopt sum, headers, module dir, MySQL)
#   make check           compile-only matrix against every header bundle under $(BUNDLES) (+ the local build)
#   make install         back up the old module (.so.bak.<timestamp>) and install the new one + conf sample
#   make uninstall       remove the module from the Asterisk module directory (backups are kept)
#   make load|unload|reload   via 'asterisk -rx' WITH reply parsing (its exit code is always 0)
#   make installer       regenerate install.sh from the sources (tools/gen-installer.sh)
#   make test            run test/run.sh if present
#   make clean
#
# Detection is done by ./ast-detect.sh (the same file install.sh embeds), so make and the installer
# always agree.  Overrides, all optional, on the command line or in the environment:
#   ASTERISK=/path/asterisk  ASTVERSION=16.30.1-vici  ASTBUILDSUM=<32hex>  ASTMODDIR=/path/modules
#   ASTTOPDIR=/usr/src/asterisk-16.30.1-vici | ASTINCDIR=/path/include   AST_SRC_ROOTS=.. AST_INC_ROOTS=..
#   ASTNOCHECK=1  accept headers whose AST_BUILDOPT_SUM / version cannot be verified (loader may refuse)
#   MYSQL=auto|1|0  MYSQL_CFLAGS=.. MYSQL_LIBS=..   phone/country lookup in vicidial_auto_calls (-DHAVE_MYSQL)
#   WERROR=1        treat warnings as errors (CI)     CFLAGS=.. EXTRA_CPPFLAGS=..   BUNDLES=/path/to/bundles
#
# Every detected value is assigned with ':=' exactly once per make invocation.

SHELL    := /bin/sh
MODULE   := app_amd_ws
MYSQL    ?= auto
ASTNOCHECK ?= 0
BUNDLES  ?= bundles
ASTETCDIR ?= /etc/asterisk
CONF_SAMPLE := amd_ws.conf.sample
DETECT_SH := ./ast-detect.sh

# goals that need neither headers nor a daemon skip detection entirely (instant 'make clean')
NODETECT_GOALS := clean distclean help installer
ifeq ($(filter-out $(NODETECT_GOALS),$(or $(MAKECMDGOALS),all)),)
  DETECT := 0
else
  DETECT := 1
endif
HDR_GOALS := all $(MODULE).so $(MODULE).o check install test

ifeq ($(DETECT),1)
# ---- Asterisk: run the detector once, import its result ------------------------------------
# Overrides are passed explicitly; the detector treats an empty value as "not set".
_det := $(shell ASTERISK='$(ASTERISK)' ASTVERSION='$(ASTVERSION)' ASTBUILDSUM='$(ASTBUILDSUM)' \
                ASTINCDIR='$(ASTINCDIR)' ASTTOPDIR='$(ASTTOPDIR)' ASTMODDIR='$(ASTMODDIR)' \
                AST_SRC_ROOTS='$(AST_SRC_ROOTS)' AST_INC_ROOTS='$(AST_INC_ROOTS)' \
                ASTNOCHECK='$(ASTNOCHECK)' AST_TIMEOUT='$(AST_TIMEOUT)' \
                $(SHELL) $(DETECT_SH) --make > .ast-detect.mk || echo FAIL)
include .ast-detect.mk
# .ast-detect.mk redefines the override variables from what the detector settled on
ifneq ($(AST_DETECT_RC),0)
  ifneq ($(filter $(HDR_GOALS),$(or $(MAKECMDGOALS),all)),)
    $(error no usable Asterisk headers for the running Asterisk - read the [ast-detect] lines above)
  endif
endif
$(info [ast-detect] Asterisk $(or $(ASTVERSION),unknown) via $(ASTVERSION_SRC); binary $(or $(ASTERISK),none) ($(ASTERISK_SRC)); modules $(or $(ASTMODDIR),unknown))
$(info [ast-detect] AST_BUILDOPT_SUM $(or $(ASTBUILDSUM),unknown) via $(ASTBUILDSUM_SRC); headers $(or $(ASTINCDIR),none) ($(ASTINCDIR_SRC)))

# ---- MySQL/MariaDB client: MYSQL=auto|1|0, overridable with MYSQL_CFLAGS/MYSQL_LIBS ----------
ifneq ($(MYSQL),0)
  ifneq ($(strip $(MYSQL_CFLAGS)$(MYSQL_LIBS)),)
    MYSQL_HOW := MYSQL_CFLAGS/MYSQL_LIBS
  else
    MYSQL_PC := $(firstword $(foreach p,libmariadb mariadb mysqlclient,$(if $(shell pkg-config --exists $(p) 2>/dev/null && echo y),$(p))))
    ifneq ($(MYSQL_PC),)
      MYSQL_CFLAGS := $(shell pkg-config --cflags $(MYSQL_PC) 2>/dev/null)
      MYSQL_LIBS   := $(shell pkg-config --libs $(MYSQL_PC) 2>/dev/null)
      MYSQL_HOW    := pkg-config $(MYSQL_PC)
    else
      MYSQL_CONFIG := $(firstword $(shell command -v mariadb_config mysql_config 2>/dev/null))
      ifneq ($(MYSQL_CONFIG),)
        MYSQL_CFLAGS := $(shell $(MYSQL_CONFIG) --cflags 2>/dev/null)
        MYSQL_LIBS   := $(shell $(MYSQL_CONFIG) --libs 2>/dev/null)
        MYSQL_HOW    := $(MYSQL_CONFIG)
      endif
    endif
  endif
  ifeq ($(strip $(MYSQL_LIBS)),)
    ifeq ($(MYSQL),1)
      $(error MYSQL=1 but no MySQL/MariaDB client development files found (pkg-config libmariadb/mariadb/mysqlclient, mariadb_config or mysql_config). Install libmariadb-devel / mariadb-connector-c-devel / libmariadb-dev, or pass MYSQL_CFLAGS= MYSQL_LIBS=)
    endif
    HAVE_MYSQL := 0
    $(info [ast-detect] MySQL: no (client development files not found; phone/country lookup disabled))
  else
    HAVE_MYSQL := 1
    $(info [ast-detect] MySQL: yes ($(MYSQL_HOW)) -> $(MYSQL_LIBS))
  endif
else
  HAVE_MYSQL := 0
  MYSQL_CFLAGS :=
  MYSQL_LIBS :=
  $(info [ast-detect] MySQL: no (MYSQL=0))
endif
endif  # DETECT

# ---- flags ----------------------------------------------------------------------------------
CC       := $(if $(filter default undefined,$(origin CC)),gcc,$(CC))
CFLAGS   ?= -O2 -g
# -MD (not -MMD): the .d must list system headers too, so the provenance gate below can see an
# accidental fall-through to /usr/include/asterisk/*.h
override CFLAGS += -pthread -fPIC -std=gnu99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wshadow -MD -MP
ifeq ($(WERROR),1)
  override CFLAGS += -Werror
endif
# Asterisk headers as system headers (-isystem) so -Wextra does not report Asterisk's own header
# style (e.g. 'inline not at beginning of declaration' in strings.h); /usr/include and
# /usr/local/include stay -I because -isystem would reorder the compiler's own include chain
AST_INC_FLAG = $(if $(filter /usr/include /usr/local/include,$(1)),-I$(1),-isystem $(1))
CPPFLAGS += $(call AST_INC_FLAG,$(ASTINCDIR)) -DAST_MODULE=\"$(MODULE)\" -DAST_MODULE_SELF_SYM=__internal_$(MODULE)_self
ifeq ($(HAVE_MYSQL),1)
  CPPFLAGS += -DHAVE_MYSQL $(MYSQL_CFLAGS)
endif
CPPFLAGS += $(EXTRA_CPPFLAGS)
LDFLAGS  += -pthread -shared
# LIBS is composed from independent parts; nothing ever re-assigns it
LIBS      = $(if $(filter 1,$(HAVE_MYSQL)),$(MYSQL_LIBS)) $(EXTRA_LIBS)

# symbols an Asterisk module may leave undefined: provided by the core at dlopen (ast_*, ao2, pbx_*)
# or by res_http_websocket.so (ast_websocket_*, a required module that exports global symbols)
CORE_SYM_RE := ^(ast_|__ast_|ao2_|__ao2_|pbx_|ast_websocket_)

# stamp with everything that influences the object: a change of headers/version/sum/flags rebuilds
BUILDFLAGS := $(ASTVERSION) $(ASTINCDIR) $(ASTBUILDSUM) $(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) $(LIBS)

.PHONY: all check install uninstall clean distclean show-config installer test load unload reload help FORCE

all: $(MODULE).so

.buildflags: FORCE
	@echo '$(BUILDFLAGS)' | cmp -s - $@ 2>/dev/null || echo '$(BUILDFLAGS)' > $@

$(MODULE).o: $(MODULE).c .buildflags
	@echo "  [CC] $< -> $@   (Asterisk $(ASTVERSION), headers $(ASTINCDIR))"
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<
	@# gate 1: every Asterisk header actually used must come from ASTINCDIR (no silent /usr/include mix)
	@bad=$$(tr ' \\' '\n\n' < $(MODULE).d | grep -E '/asterisk(\.h|/[^/]*\.h)$$' | grep -v "^$(ASTINCDIR)/" | sort -u); \
	 if [ -n "$$bad" ]; then echo "ERROR: Asterisk headers pulled from outside $(ASTINCDIR):"; echo "$$bad" | sed 's/^/    /'; rm -f $@; exit 1; fi
	@# gate 2: the object embeds the core's AST_BUILDOPT_SUM (the loader compares it)
	@if [ -n '$(ASTBUILDSUM)' ]; then strings -a $@ | grep -qx '$(ASTBUILDSUM)' || { echo "ERROR: $@ does not embed AST_BUILDOPT_SUM $(ASTBUILDSUM)"; rm -f $@; exit 1; }; fi

$(MODULE).so: $(MODULE).o
	@echo "  [LD] $< -> $@"
	$(CC) $(LDFLAGS) -o $@ $< $(LIBS)
	@# post-link gate 3: every symbol still undefined must be one the core (or res_http_websocket) provides
	@und=$$(ldd -r $@ 2>&1 | awk '/undefined symbol/{sub(/[[:space:]]*\(.*/,"",$$3); print $$3}' | sort -u); \
	 if [ -n '$(ASTERISK)' ] && [ -r '$(ASTERISK)' ] && nm -D --defined-only '$(ASTERISK)' >/dev/null 2>&1; then \
	   core=$$(nm -D --defined-only '$(ASTERISK)' | awk '{print $$NF}' | sed 's/@.*//' | sort -u); \
	   missing=$$(printf '%s\n' "$$und" | grep -v -E '$(CORE_SYM_RE)' ; printf '%s\n' "$$und" | grep -E '$(CORE_SYM_RE)' | grep -v '^ast_websocket_' | grep -vxF "$$core" ); \
	 else \
	   echo "  [..] no readable core binary - symbol check limited to the name pattern"; \
	   missing=$$(printf '%s\n' "$$und" | grep -v -E '$(CORE_SYM_RE)'); \
	 fi; \
	 missing=$$(printf '%s\n' "$$missing" | grep -v '^$$' || true); \
	 if [ -n "$$missing" ]; then echo "ERROR: $@ needs symbols that neither its libraries nor Asterisk provide (dlopen would fail):"; echo "$$missing" | sed 's/^/    /'; rm -f $@; exit 1; fi; \
	 echo "  [OK] undefined symbols of $@ are all provided by Asterisk$(if $(filter 1,$(HAVE_MYSQL)), or the MySQL client library)"
	@# post-link gate 4: the .so embeds the core's sum
	@if [ -n '$(ASTBUILDSUM)' ]; then strings -a $@ | grep -qx '$(ASTBUILDSUM)' && echo "  [OK] $@ embeds AST_BUILDOPT_SUM $(ASTBUILDSUM)" || { echo "ERROR: $@ does not embed AST_BUILDOPT_SUM $(ASTBUILDSUM)"; rm -f $@; exit 1; }; \
	 else echo "  [..] core AST_BUILDOPT_SUM unknown - not verified"; fi

# ---- check: compile-only matrix against header bundles (tools/make-header-bundle.sh output) ----
# Bundles are directories $(BUNDLES)/asterisk-<ver>/include (tarballs asterisk-<ver>-headers.tar.gz
# found there are extracted first).  Bundles ship no buildopts.h: one is synthesised for the core's
# sum (or the stock OPTIONAL_API sum when unknown), exactly as install.sh does on a customer box.
CHECK_SUM := $(or $(ASTBUILDSUM),da6642af068ee5e6490c5b1d2cc1d238)
CHECK_CPPFLAGS := $(filter-out -I$(ASTINCDIR) -isystem $(ASTINCDIR),$(CPPFLAGS))
check: all
	@set -e; found=0; \
	 for tb in $(BUNDLES)/asterisk-*-headers.tar.gz; do \
	   [ -f "$$tb" ] || continue; d=$${tb%-headers.tar.gz}; \
	   [ -f "$$d/include/asterisk.h" ] || { echo "  [check] extracting $$tb"; mkdir -p "$$d"; tar xzf "$$tb" -C "$$d" --strip-components=1; }; \
	 done; \
	 for inc in $(BUNDLES)/asterisk-*/include; do \
	   [ -f "$$inc/asterisk.h" ] || continue; found=$$((found+1)); tree=$${inc%/include}; name=$${tree##*/}; \
	   [ -f "$$inc/asterisk/buildopts.h" ] || { . $(DETECT_SH); ast_synth_buildopts "$$inc" '$(CHECK_SUM)'; }; \
	   printf '  [check] %-28s ' "$$name"; \
	   $(CC) $(CHECK_CPPFLAGS) -isystem "$$inc" $(CFLAGS) -c -o "$$tree/$(MODULE).o" $(MODULE).c || { echo "FAILED (compile)"; exit 1; }; \
	   bad=$$(tr ' \\' '\n\n' < "$$tree/$(MODULE).d" | grep -E '/asterisk(\.h|/[^/]*\.h)$$' | grep -v "^$$inc/" | sort -u); \
	   [ -z "$$bad" ] || { echo "FAILED (headers from outside the bundle: $$bad)"; exit 1; }; \
	   echo "OK ($$(sed -n 1p "$$tree/.version" 2>/dev/null || echo 'no .version'))"; \
	 done; \
	 if [ $$found -eq 0 ]; then echo "  [check] no header bundles under $(BUNDLES) (see tools/make-header-bundle.sh) - only the local build was checked"; fi

# ---- install / uninstall -------------------------------------------------------------------
install: $(MODULE).so
	@[ -n "$(ASTMODDIR)" ] && [ -d "$(DESTDIR)$(ASTMODDIR)" ] || { echo "ERROR: Asterisk module directory not found - pass ASTMODDIR=/path/to/modules"; exit 1; }
	@if [ -f "$(DESTDIR)$(ASTMODDIR)/$(MODULE).so" ]; then \
	   b="$(DESTDIR)$(ASTMODDIR)/$(MODULE).so.bak.$$(date +%Y%m%d%H%M%S)"; cp -p "$(DESTDIR)$(ASTMODDIR)/$(MODULE).so" "$$b"; echo "  [BACKUP] $$b"; fi
	install -m 755 $(MODULE).so "$(DESTDIR)$(ASTMODDIR)/.$(MODULE).so.new"
	mv -f "$(DESTDIR)$(ASTMODDIR)/.$(MODULE).so.new" "$(DESTDIR)$(ASTMODDIR)/$(MODULE).so"
	@echo "  [INSTALL] $(DESTDIR)$(ASTMODDIR)/$(MODULE).so"
	@if [ -f $(CONF_SAMPLE) ] && [ -d "$(DESTDIR)$(ASTETCDIR)" ]; then install -m 644 $(CONF_SAMPLE) "$(DESTDIR)$(ASTETCDIR)/$(CONF_SAMPLE)"; echo "  [INSTALL] $(DESTDIR)$(ASTETCDIR)/$(CONF_SAMPLE)"; fi
	@echo "  next: make reload   (or: asterisk -rx 'module load $(MODULE).so')"

uninstall:
	@[ -n "$(ASTMODDIR)" ] || { echo "ERROR: Asterisk module directory not found - pass ASTMODDIR=/path/to/modules"; exit 1; }
	rm -f "$(DESTDIR)$(ASTMODDIR)/$(MODULE).so"
	@echo "  [REMOVED] $(DESTDIR)$(ASTMODDIR)/$(MODULE).so (backups $(MODULE).so.bak.* kept, amd_ws.conf kept)"

# ---- load / unload / reload: 'asterisk -rx' exits 0 whatever happened, so parse the reply ------
define ast_rx
$(SHELL) -c 'timeout $(or $(AST_TIMEOUT),5) "$(ASTERISK)" $(ASTERISK_OPTS) -rx "$(1)" 2>&1'
endef
ast_status = $(SHELL) -c '$(call ast_rx,module show like $(MODULE)) | awk -v m="$(MODULE).so" '"'"'$$1==m'"'"

load:
	@[ -n "$(ASTERISK)" ] || { echo "ERROR: no asterisk binary"; exit 1; }
	@out=$$($(call ast_rx,module load $(MODULE).so)); echo "  $$out"; \
	 case "$$out" in "Loaded "*) ;; *) echo "ERROR: module load failed (check /var/log/asterisk/messages)"; exit 1;; esac
	@$(ast_status) | grep -q ' Running ' && echo "  [OK] $(MODULE).so is Running" || { echo "ERROR: $(MODULE).so not Running"; exit 1; }

unload:
	@[ -n "$(ASTERISK)" ] || { echo "ERROR: no asterisk binary"; exit 1; }
	@out=$$($(call ast_rx,module unload $(MODULE).so)); echo "  $$out"; \
	 case "$$out" in "Unloaded "*) ;; *) echo "ERROR: module unload refused (module in use by a call? try again when idle)"; exit 1;; esac

reload: unload load

# ---- misc ---------------------------------------------------------------------------------
show-config:
	@echo "ASTERISK=$(ASTERISK)"; echo "ASTVERSION=$(ASTVERSION)"; echo "ASTVERBASE=$(ASTVERBASE)"; echo "ASTMAJOR=$(ASTMAJOR)"
	@echo "ASTBUILDSUM=$(ASTBUILDSUM)"; echo "ASTINCDIR=$(ASTINCDIR)"; echo "ASTMODDIR=$(ASTMODDIR)"
	@echo "MySQL: $(if $(filter 1,$(HAVE_MYSQL)),yes ($(MYSQL_HOW)),no)"
	@echo "CC=$(CC)"; echo "CFLAGS=$(CFLAGS)"; echo "CPPFLAGS=$(CPPFLAGS)"; echo "LIBS=$(LIBS)"

installer:
	$(SHELL) tools/gen-installer.sh -o install.sh

test:
	@if [ -x test/run.sh ]; then test/run.sh; else echo "no test/run.sh in this checkout"; fi

clean:
	rm -f $(MODULE).o $(MODULE).so $(MODULE).d .buildflags .ast-detect.mk

distclean: clean
	rm -rf bundles/asterisk-*/$(MODULE).o bundles/asterisk-*/$(MODULE).d

help:
	@sed -n '2,22p' Makefile

-include $(MODULE).d
FORCE:
__APP_AMD_WS_EMBED_EOF__
    cat > "$d/ast-detect.sh" <<'__APP_AMD_WS_EMBED_EOF__'
#!/bin/sh
# ast-detect.sh - find the Asterisk that is RUNNING (else installed) on this box and a header
# tree that matches it.  Shared by the Makefile and by install.sh (embedded verbatim), so both
# always take the same decision.
#
# POSIX sh (tested with dash and bash).  Every diagnostic goes to STDERR, so callers can use
# $(...) safely; nothing but the requested output ever appears on stdout.
#
# Usage as a library:
#     . ./ast-detect.sh; ast_detect || exit 1
#     make ASTERISK="$ASTERISK" ASTVERSION="$ASTVERSION" ASTBUILDSUM="$ASTBUILDSUM" ASTINCDIR="$ASTINCDIR" ...
# Usage standalone:
#     sh ast-detect.sh            -> KEY=VALUE lines (shell syntax) on stdout, rc 0 = usable headers found
#     sh ast-detect.sh --make     -> KEY := VALUE lines (GNU make syntax) on stdout, rc 0 = usable headers found
#     sh ast-detect.sh --running  -> rc 0 if an Asterisk daemon answers 'core show version' within AST_TIMEOUT
#
# Overrides (environment, or on the make command line):
#     ASTERISK=/path/to/asterisk        the binary to fingerprint (default: the running daemon's image)
#     ASTERISK_OPTS='-C /etc/asterisk/asterisk.conf'   extra options for 'asterisk -rx' (auto: the daemon's -C)
#     ASTVERSION=16.30.1-vici           skip version detection
#     ASTBUILDSUM=<32 hex>              skip AST_BUILDOPT_SUM detection
#     ASTINCDIR=/path/include           use exactly this include dir (still validated unless ASTNOCHECK=1)
#     ASTTOPDIR=/path/asterisk-<ver>    use <ASTTOPDIR>/include (same rules)
#     ASTMODDIR=/path/modules           skip module-directory detection
#     AST_SRC_ROOTS="/usr/src ..."      where versioned source trees are searched
#     AST_INC_ROOTS="/usr/include ..."  where installed headers are searched
#     ASTNOCHECK=1                      downgrade a buildopt-sum mismatch / unverifiable headers to a WARNING
#     AST_TIMEOUT=5                     seconds allowed for every 'asterisk -rx' / 'asterisk -V' call
#
# Why all this: an out-of-tree module needs only headers, but they must belong to the same
# Asterisk version as the running core AND carry the same AST_BUILDOPT_SUM (main/loader.c refuses
# the module otherwise).  /usr/include, a distro -dev package and stray trees in /usr/src may all
# be from a different Asterisk than the one that is running, so every candidate is validated.

LC_ALL=C; export LC_ALL

AST_TIMEOUT=${AST_TIMEOUT:-5}
AST_SRC_ROOTS=${AST_SRC_ROOTS:-"/usr/src /usr/src/asterisk /usr/local/src /usr/local/src/asterisk"}
AST_INC_ROOTS=${AST_INC_ROOTS:-"/usr/include /usr/local/include"}
ASTNOCHECK=${ASTNOCHECK:-0}

ad_log()  { printf '[ast-detect] %s\n' "$*" >&2; }
ad_warn() { printf '[ast-detect] WARNING: %s\n' "$*" >&2; }
ad_err()  { printf '[ast-detect] ERROR: %s\n' "$*" >&2; }
ad_run()  { timeout "$AST_TIMEOUT" "$@" 2>/dev/null; }     # never hang on a broken/deadlocked binary

# ---------------------------------------------------------------------------------------------
# 1. binary: image of the running daemon (skipping 'asterisk -r' consoles) -> PATH -> well-known
# ---------------------------------------------------------------------------------------------
ast_daemon_pid() {
    # prints the PID of the daemon (not of a remote console), or nothing
    for p in $(pgrep -x asterisk 2>/dev/null); do
        tr '\0' ' ' < "/proc/$p/cmdline" 2>/dev/null | grep -- ' -r' >/dev/null && continue
        printf '%s\n' "$p"; return 0
    done
    return 1
}

# '-C <file>' of the daemon's command line, so that 'asterisk -rx' reaches a daemon started with a
# non-default asterisk.conf (its control socket lives wherever that file says)
ast_ctl_opts_of() { tr '\0' '\n' < "/proc/$1/cmdline" 2>/dev/null | awk '$0 == "-C" { getline f; printf "-C %s", f; exit }'; }

ast_find_binary() {
    ASTERISK_OPTS=${ASTERISK_OPTS:-}
    [ -n "${ASTERISK:-}" ] && { ASTERISK_SRC=override; return 0; }
    ASTERISK=''; ASTERISK_SRC=''
    p=$(ast_daemon_pid) || p=''
    if [ -n "$p" ]; then
        ASTERISK=$(readlink "/proc/$p/exe" 2>/dev/null | sed 's/ (deleted)$//')
        [ -n "$ASTERISK" ] && { ASTERISK_SRC="running process $p"; ASTERISK_OPTS=$(ast_ctl_opts_of "$p"); }
    fi
    [ -z "$ASTERISK" ] && { ASTERISK=$(command -v asterisk 2>/dev/null); ASTERISK_SRC=PATH; }
    if [ -z "$ASTERISK" ]; then
        for b in /usr/sbin/asterisk /usr/local/sbin/asterisk; do
            [ -x "$b" ] && { ASTERISK=$b; ASTERISK_SRC="well-known path"; break; }
        done
    fi
    [ -n "$ASTERISK" ] || ASTERISK_SRC="none found"
    [ -n "$ASTERISK" ]
}

# rc 0 when a daemon answers the CLI (the only reliable definition of "running")
ast_running() {
    [ -n "${ASTERISK:-}" ] || ast_find_binary || return 1
    # shellcheck disable=SC2086
    ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show version' | grep '^Asterisk ' >/dev/null
}

# ---------------------------------------------------------------------------------------------
# 2. version: 'core show version' -> 'asterisk -V' -> embedded string pair ("16.30.1-vici" + "163001")
# ---------------------------------------------------------------------------------------------
ast_version_filter() { sed -n 's/^Asterisk \([^ ][^ ]*\).*/\1/p' | head -n 1; }

# main/version.c stores the version string and its numeric form next to each other; requiring both
# avoids false hits like "10.0" from unrelated strings.
ast_version_from_strings() {
    strings -a "$1" 2>/dev/null | awk '
        /^[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)?(-[A-Za-z0-9.]+)?$/ || /^certified\/[0-9][0-9]*\.[0-9][0-9]*(-cert[0-9]+)?$/ { v[$0]=1 }
        /^[0-9][0-9][0-9][0-9][0-9][0-9]?$/ { n[$0]=1 }
        END { for (s in v) { t=s; sub(/^certified\//,"",t); sub(/-cert/,".",t); split(t,a,/[.-]/);
              if (sprintf("%d%02d%02d",a[1],a[2],a[3]) in n) print s } }' | sort -u | head -n 1
}

ast_find_version() {
    if [ -n "${ASTVERSION:-}" ]; then ASTVERSION_SRC=override
    else
        ASTVERSION=''; ASTVERSION_SRC=unknown
        if [ -n "${ASTERISK:-}" ]; then
            # shellcheck disable=SC2086
            ASTVERSION=$(ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show version' | ast_version_filter); ASTVERSION_SRC="running daemon (core show version)"
            if [ -z "$ASTVERSION" ]; then ASTVERSION=$(ad_run "$ASTERISK" -V | ast_version_filter); ASTVERSION_SRC="'$ASTERISK -V' (daemon not running; version on disk)"; fi
            if [ -z "$ASTVERSION" ]; then ASTVERSION=$(ast_version_from_strings "$ASTERISK"); ASTVERSION_SRC="strings(1) on $ASTERISK (binary does not run here)"; fi
            [ -n "$ASTVERSION" ] || ASTVERSION_SRC=unknown
            # binary on disk replaced after the daemon started?  Build for the RUNNING one, but say so.
            case $ASTVERSION_SRC in "running daemon"*)
                dv=$(ad_run "$ASTERISK" -V | ast_version_filter)
                [ -n "$dv" ] && [ "$dv" != "$ASTVERSION" ] && ad_warn "running Asterisk is $ASTVERSION but the binary on disk is $dv (restart pending?) - building for the RUNNING one";;
            esac
        fi
    fi
    # 16.30.1-vici -> 16.30.1 ; certified/18.9-cert1 -> 18.9 ; 18.10.0~dfsg... -> 18.10.0 ; GIT-... -> empty
    ASTVERBASE=$(printf '%s\n' "$ASTVERSION" | sed -n 's|^certified/||; s|^\([0-9][0-9]*\(\.[0-9][0-9]*\)\{1,2\}\).*|\1|p')
    ASTMAJOR=${ASTVERBASE%%.*}
    [ -n "$ASTVERSION" ]
}

# ---------------------------------------------------------------------------------------------
# 3. module dir: 'core show settings' -> asterisk.conf astmoddir -> first known dir holding pbx_config.so
# ---------------------------------------------------------------------------------------------
AST_MODDIR_CANDS="/usr/lib64/asterisk/modules /usr/lib/asterisk/modules /usr/lib/x86_64-linux-gnu/asterisk/modules /usr/local/lib/asterisk/modules /usr/local/lib64/asterisk/modules"

ast_find_moddir() {
    [ -n "${ASTMODDIR:-}" ] && { ASTMODDIR_SRC=override; return 0; }
    ASTMODDIR=''; ASTMODDIR_SRC=''
    if [ -n "${ASTERISK:-}" ]; then
        # shellcheck disable=SC2086
        ASTMODDIR=$(ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx 'core show settings' | sed -n 's/^ *Module directory: *//p' | head -n 1)
        [ -n "$ASTMODDIR" ] && ASTMODDIR_SRC="running daemon (core show settings)"
    fi
    if [ -z "$ASTMODDIR" ]; then
        ASTMODDIR=$(sed -n 's/^ *astmoddir *=> *\([^ ;]*\).*/\1/p' /etc/asterisk/asterisk.conf 2>/dev/null | head -n 1)
        [ -n "$ASTMODDIR" ] && ASTMODDIR_SRC="/etc/asterisk/asterisk.conf"
    fi
    if [ -z "$ASTMODDIR" ]; then
        for d in $AST_MODDIR_CANDS; do
            [ -f "$d/pbx_config.so" ] && { ASTMODDIR=$d; ASTMODDIR_SRC="contains pbx_config.so"; break; }
        done
    fi
    [ -n "$ASTMODDIR" ] || ASTMODDIR_SRC="not found"
    [ -n "$ASTMODDIR" ]
}

# ---------------------------------------------------------------------------------------------
# 4. AST_BUILDOPT_SUM of the core: the most frequent 32-hex string in the binary (one copy per
#    built-in module), else in a stock module.  NOT the 'Build Options' line of 'core show
#    settings' - that string also lists non-ABI flags (BUILD_NATIVE, ...) and is not the md5 input.
# ---------------------------------------------------------------------------------------------
ast_sum_of() { strings -a "$1" 2>/dev/null | grep -xE '[0-9a-f]{32}' | sort | uniq -c | sort -rn | awk 'NR==1{print $2}'; }

ast_find_buildsum() {
    [ -n "${ASTBUILDSUM:-}" ] && { ASTBUILDSUM_SRC=override; return 0; }
    ASTBUILDSUM=''; ASTBUILDSUM_SRC=''
    if [ -n "${ASTERISK:-}" ] && [ -r "$ASTERISK" ]; then
        ASTBUILDSUM=$(ast_sum_of "$ASTERISK"); ASTBUILDSUM_SRC="strings(1) on $ASTERISK"
    fi
    if [ -z "$ASTBUILDSUM" ] && [ -n "${ASTMODDIR:-}" ]; then
        for m in "$ASTMODDIR/pbx_config.so" "$ASTMODDIR/app_dial.so" "$ASTMODDIR/res_http_websocket.so"; do
            [ -f "$m" ] || continue
            ASTBUILDSUM=$(ast_sum_of "$m"); ASTBUILDSUM_SRC="strings(1) on $m"
            [ -n "$ASTBUILDSUM" ] && break
        done
    fi
    [ -n "$ASTBUILDSUM" ] || ASTBUILDSUM_SRC="unknown (no readable core binary or stock module)"
    [ -n "$ASTBUILDSUM" ]
}

# md5 of the ', '-joined ABI-relevant menuselect options + newline (build_tools/make_buildopts_h)
ast_sum_for_opts() { printf '%s\n' "$1" | md5sum | cut -c1-32; }

# Print the option list behind a known AST_BUILDOPT_SUM, or fail (rc 1) for an unknown sum.
# The candidates are the ABI-relevant options of menuselect (build_tools/cflags.xml order), in
# every combination, so any Asterisk >= 16 built from stock menuselect flags is covered.
# Asterisk 13 puts MALLOC_DEBUG/REF_DEBUG/LOW_MEMORY into the sum as well; 13 is out of scope.
ast_opts_for_sum() {
    _sum=$1
    case $_sum in
        da6642af068ee5e6490c5b1d2cc1d238) printf 'OPTIONAL_API\n'; return 0;;                  # stock 16/18/20/21/22 (ViciDial, ViciBox RPM)
        fa819827cbff2ea35341af5458859233) printf 'LOADABLE_MODULES, OPTIONAL_API\n'; return 0;; # stock 13
    esac
    # brute force over the ordered option set (2^9 = 512 md5 calls, about a second)
    _n=0
    while [ $_n -lt 512 ]; do
        _opts=''; _i=0
        for _o in DEBUG_THREADLOCALS DO_CRASH TEST_FRAMEWORK DEBUG_THREADS DEBUG_FD_LEAKS LOADABLE_MODULES OPTIONAL_API G711_NEW_ALGORITHM INTEGER_CALLERID; do
            if [ $(( (_n >> _i) & 1 )) -eq 1 ]; then
                _opts="${_opts:+$_opts, }$_o"
            fi
            _i=$((_i+1))
        done
        if [ -n "$_opts" ] && [ "$(ast_sum_for_opts "$_opts")" = "$_sum" ]; then printf '%s\n' "$_opts"; return 0; fi
        _n=$((_n+1))
    done
    return 1
}

# ast_synth_buildopts <include dir> <sum>: write <include dir>/asterisk/buildopts.h for a known sum.
# Used when only pristine headers are available (vendor header bundle, headers-only tarball extract).
ast_synth_buildopts() {
    _inc=$1; _sum=$2
    [ -n "$_sum" ] || { ad_err "cannot synthesise buildopts.h: AST_BUILDOPT_SUM of the running Asterisk is unknown"; return 1; }
    _opts=$(ast_opts_for_sum "$_sum") || { ad_err "AST_BUILDOPT_SUM $_sum is not one produced by stock menuselect options (custom build) - use the real configured+built source tree: ASTTOPDIR=/path/to/asterisk-<ver>"; return 1; }
    [ "$(ast_sum_for_opts "$_opts")" = "$_sum" ] || { ad_err "internal error: option list '$_opts' does not hash to $_sum"; return 1; }
    mkdir -p "$_inc/asterisk" || return 1
    {
        printf '/*\n * buildopts.h\n * Synthesised by ast-detect.sh for AST_BUILDOPT_SUM %s\n * (the running Asterisk was built with: %s)\n */\n\n' "$_sum" "$_opts"
        for _o in $(printf '%s' "$_opts" | tr -d ','); do printf '#define %s 1\n' "$_o"; done
        printf '#define AST_BUILDOPT_SUM "%s"\n' "$_sum"
        printf '#define AST_BUILDOPTS "%s"\n' "$_opts"
        printf '#define AST_BUILDOPTS_ALL "%s"\n' "$_opts"
    } > "$_inc/asterisk/buildopts.h" || return 1
    ad_log "synthesised $_inc/asterisk/buildopts.h (AST_BUILDOPTS \"$_opts\", sum $_sum)"
}

# ---------------------------------------------------------------------------------------------
# 5. validate one include dir.  rc 0 = usable; one '[ast-detect] accept/reject <dir>: <why>' line
#    on stderr.  Rules: asterisk.h + asterisk/autoconfig.h (configured) + asterisk/buildopts.h
#    (built or synthesised) must exist; the tree's .version must agree with the running version
#    when present; AST_BUILDOPT_SUM must equal the core's (mismatch = reject, ASTNOCHECK=1 = warn).
#    Installed headers without .version are tied to the binary by package version or by
#    install-time proximity (make install writes both within seconds); otherwise a WARNING.
# ---------------------------------------------------------------------------------------------
ast_check_incdir() {
    d=$1; why=''; note=''
    if   [ ! -f "$d/asterisk.h" ];            then why='no asterisk.h'
    elif [ ! -f "$d/asterisk/autoconfig.h" ]; then why='not configured (no asterisk/autoconfig.h)'
    elif [ ! -f "$d/asterisk/buildopts.h" ];  then why='not built (no asterisk/buildopts.h - ./configure alone is not enough)'
    else
        sum=$(sed -n 's/^#define AST_BUILDOPT_SUM "\([0-9a-f]*\)".*/\1/p' "$d/asterisk/buildopts.h" | head -n 1)
        # the candidate's OWN tree dir (not '$d/..', which would follow a symlinked include/ elsewhere)
        tv=$(sed -n 1p "${d%/include}/.version" 2>/dev/null)
        if [ -n "$tv" ] && [ -n "${ASTVERSION:-}" ] && [ "$tv" != "$ASTVERSION" ] && [ "$tv" != "$ASTVERBASE" ]; then
            why="tree version $tv != running $ASTVERSION"
        elif [ -n "${ASTBUILDSUM:-}" ] && [ "$sum" != "$ASTBUILDSUM" ]; then
            if [ "$ASTNOCHECK" = 1 ]; then note="WARNING: AST_BUILDOPT_SUM ${sum:-none} != core $ASTBUILDSUM, accepted because ASTNOCHECK=1"
            else why="AST_BUILDOPT_SUM ${sum:-none} != core $ASTBUILDSUM (Asterisk would refuse to load the module)"; fi
        elif [ -z "$tv" ]; then
            pv=''
            if command -v rpm >/dev/null 2>&1; then pv=$(rpm -qf --qf '%{VERSION}' "$d/asterisk.h" 2>/dev/null | grep -v 'not owned'); fi
            if [ -z "$pv" ] && command -v dpkg-query >/dev/null 2>&1; then
                pkg=$(dpkg -S "$d/asterisk.h" 2>/dev/null | sed 's/:.*//;q')
                [ -n "$pkg" ] && pv=$(dpkg-query -W -f '${Version}' "$pkg" 2>/dev/null)
            fi
            pv=$(printf '%s' "$pv" | sed 's/^[0-9]*://')
            bm=$(stat -c %Y "${ASTERISK:-/nonexistent}" 2>/dev/null || echo 0); hm=$(stat -c %Y "$d/asterisk/buildopts.h" 2>/dev/null || echo 0)
            delta=$(( bm - hm )); [ $delta -lt 0 ] && delta=$(( -delta ))
            if   [ -n "$pv" ] && [ -n "$ASTVERBASE" ] && [ "${pv#"$ASTVERBASE"}" != "$pv" ]; then note="installed headers owned by package version $pv (matches running $ASTVERSION)"
            elif [ -n "$pv" ] && [ -n "$ASTVERBASE" ] && [ $delta -gt 3600 ]; then
                if [ "$ASTNOCHECK" = 1 ]; then note="WARNING: installed headers belong to package version $pv, running $ASTVERSION; accepted because ASTNOCHECK=1"
                else why="installed headers belong to package version $pv, running $ASTVERSION (and not rewritten by the same make install)"; fi
            elif [ $delta -le 3600 ] && [ "$bm" -gt 0 ]; then note="installed headers written within ${delta}s of the binary (same make install); sum matches"
            elif [ -z "${ASTBUILDSUM:-}" ]; then note="WARNING: unversioned headers and core sum unknown - cannot verify they match the running Asterisk"
            else note="WARNING: unversioned installed headers (not from a package, not installed together with the binary); AST_BUILDOPT_SUM matches but the Asterisk major version cannot be verified - prefer ASTTOPDIR=<matching source tree>"; fi
        else note="tree .version $tv matches"; fi
    fi
    if [ -n "$why" ]; then ad_log "reject $d: $why"; return 1; fi
    ad_log "accept $d: ${note:-ok}"; return 0
}

# ---------------------------------------------------------------------------------------------
# 6. candidates in priority order; the first valid one wins.
#    ASTINCDIR / ASTTOPDIR override the list; then trees named asterisk-<exact version>, trees of
#    the same base version (asterisk-<base>, asterisk-<base>-*, asterisk-certified-<base>*) under
#    AST_SRC_ROOTS - only directories with include/asterisk.h, so *.tar.gz, sound dirs and
#    asterisk-perl-* never match - then <prefix>/include next to the binary, then AST_INC_ROOTS.
# ---------------------------------------------------------------------------------------------
ad_add() { case " $cands " in *" $1 "*) ;; *) cands="$cands $1";; esac; }

ast_find_incdir() {
    cands=''; ASTINCDIR_SRC=''
    if [ -n "${ASTINCDIR:-}" ]; then cands=$ASTINCDIR; ASTINCDIR_SRC="ASTINCDIR override"
    elif [ -n "${ASTTOPDIR:-}" ]; then cands="$ASTTOPDIR/include"; ASTINCDIR_SRC="ASTTOPDIR override"
    else
        if [ -n "${ASTVERSION:-}" ]; then
            for r in $AST_SRC_ROOTS; do t="$r/asterisk-$ASTVERSION"; [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"; done
            if [ -n "$ASTVERBASE" ]; then
                for r in $AST_SRC_ROOTS; do
                    for t in "$r/asterisk-$ASTVERBASE" "$r"/asterisk-"$ASTVERBASE"-* "$r"/asterisk-certified-"$ASTVERBASE"*; do
                        [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"
                    done
                done
            fi
        else
            for r in $AST_SRC_ROOTS; do
                for t in "$r"/asterisk-[0-9]* "$r"/asterisk-certified-*; do [ -f "$t/include/asterisk.h" ] && ad_add "$t/include"; done
            done
        fi
        case ${ASTERISK:-} in */sbin/asterisk) p=${ASTERISK%/sbin/asterisk}; [ -f "$p/include/asterisk.h" ] && ad_add "$p/include";; esac
        for r in $AST_INC_ROOTS; do [ -f "$r/asterisk.h" ] && ad_add "$r"; done
        cands=${cands# }
    fi
    ok=''; n=0
    for d in $cands; do ast_check_incdir "$d" && { ok="$ok $d"; n=$((n+1)); }; done
    ok=${ok# }
    if [ -n "${ASTINCDIR:-}" ]; then
        [ $n -eq 1 ] || [ "$ASTNOCHECK" = 1 ] || { ad_err "ASTINCDIR=$ASTINCDIR failed validation (ASTNOCHECK=1 forces it)"; return 1; }
        return 0
    fi
    if [ -n "${ASTTOPDIR:-}" ]; then
        [ $n -eq 1 ] || [ "$ASTNOCHECK" = 1 ] || { ad_err "ASTTOPDIR=$ASTTOPDIR failed validation (ASTNOCHECK=1 forces it)"; return 1; }
        ASTINCDIR="$ASTTOPDIR/include"; return 0
    fi
    if [ -z "${ASTVERSION:-}" ]; then
        # unknown version: accept only an unambiguous candidate that is tied to the core by its sum
        if [ $n -eq 1 ] && [ -n "${ASTBUILDSUM:-}" ]; then
            ASTINCDIR=$ok; ASTINCDIR_SRC="only sum-matching candidate (version unknown)"
            ad_warn "Asterisk version unknown; using the only header dir whose AST_BUILDOPT_SUM matches the core: $ASTINCDIR (pass ASTVERSION=... to be sure)"; return 0
        fi
        if [ $n -ge 1 ] && [ "$ASTNOCHECK" = 1 ]; then
            ASTINCDIR=${ok%% *}; ASTINCDIR_SRC="first candidate (version unknown, ASTNOCHECK=1)"
            ad_warn "Asterisk version unknown and ASTNOCHECK=1: using $ASTINCDIR unverified"; return 0
        fi
        ad_err "Asterisk version could not be detected ($n header dir(s) validated: ${ok:-none}) - pass ASTVERSION=<version> or ASTTOPDIR=/path/to/configured+built source tree (ASTNOCHECK=1 forces the first candidate)"
        return 1
    fi
    ASTINCDIR=${ok%% *}; ASTINCDIR_SRC="first validated candidate"
    [ -n "$ASTINCDIR" ] && return 0
    ad_err "no configured+built Asterisk $ASTVERSION headers with AST_BUILDOPT_SUM ${ASTBUILDSUM:-?} found (candidates: ${cands:-none}; roots: $AST_SRC_ROOTS $AST_INC_ROOTS)"
    ast_hint_no_headers
    return 1
}

# next steps when nothing validates (kept in one place so Makefile and installer say the same)
ast_hint_no_headers() {
    v=${ASTVERSION:-<version>}
    case $v in
        *-vici)      tb="https://download.vicidial.com/required-apps/asterisk-$v.tar.gz"; tree="asterisk-$v";;
        certified/*) tb="https://downloads.asterisk.org/pub/telephony/certified-asterisk/releases/asterisk-certified-${v#certified/}.tar.gz"; tree="asterisk-certified-${v#certified/}";;
        *)           tb="https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTVERBASE:-$v}.tar.gz (or old-releases/)"; tree="asterisk-${ASTVERBASE:-$v}";;
    esac
    ad_err "fix one of: (a) run install.sh, which fetches a header bundle or the headers of $tb and synthesises buildopts.h;"
    ad_err "             (b) extract + ./configure + 'make include/asterisk/buildopts.h' that tarball and pass ASTTOPDIR=/path/to/$tree;"
    ad_err "             (c) install the asterisk-devel/asterisk-dev package of EXACTLY the running version (only when Asterisk itself is the distro package);"
    ad_err "             (d) ASTNOCHECK=1 to accept mismatching headers at your own risk (the loader may refuse the module)."
}

# ---------------------------------------------------------------------------------------------
# all-in-one: sets ASTERISK ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR (+ *_SRC)
# ---------------------------------------------------------------------------------------------
ast_detect_core() {
    ast_find_binary   || ad_warn "no asterisk binary found (pass ASTERISK=/path/to/asterisk)"
    ast_find_version  || ad_warn "cannot determine the Asterisk version${ASTERISK:+ from $ASTERISK}"
    ast_find_moddir   || ad_warn "no Asterisk module directory found (pass ASTMODDIR=/path)"
    ast_find_buildsum || ad_warn "cannot read AST_BUILDOPT_SUM from the core or its modules"
    ad_log "binary   : ${ASTERISK:-none}${ASTERISK_OPTS:+ $ASTERISK_OPTS} ($ASTERISK_SRC)"
    ad_log "version  : ${ASTVERSION:-unknown} (base ${ASTVERBASE:-?}, major ${ASTMAJOR:-?}) via $ASTVERSION_SRC"
    ad_log "buildsum : ${ASTBUILDSUM:-unknown} via $ASTBUILDSUM_SRC"
    ad_log "moddir   : ${ASTMODDIR:-unknown} ($ASTMODDIR_SRC)"
}

ast_detect() {
    ast_detect_core
    ast_find_incdir || return 1
    ad_log "headers  : $ASTINCDIR ($ASTINCDIR_SRC)"
    export ASTERISK ASTERISK_OPTS ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR
    return 0
}

AST_DETECT_VARS="ASTERISK ASTERISK_OPTS ASTVERSION ASTVERBASE ASTMAJOR ASTBUILDSUM ASTMODDIR ASTINCDIR ASTERISK_SRC ASTVERSION_SRC ASTBUILDSUM_SRC ASTMODDIR_SRC ASTINCDIR_SRC"

ast_print_vars() {   # $1 = sh | make
    for v in $AST_DETECT_VARS; do
        eval "val=\${$v:-}"
        case $1 in
            make) printf '%s := %s\n' "$v" "$val";;
            *)    printf "%s='%s'\n" "$v" "$(printf '%s' "$val" | sed "s/'/'\\\\''/g")";;
        esac
    done
}

# standalone use (not when sourced as a library)
case ${0##*/} in
    ast-detect.sh)
        case ${1:-} in
            --running) ast_running; exit $?;;
            --make)    ast_detect; rc=$?; printf 'AST_DETECT_RC := %s\n' "$rc"; ast_print_vars make; exit $rc;;
            --help|-h) sed -n '2,32p' "$0"; exit 0;;
            *)         ast_detect; rc=$?; ast_print_vars sh; exit $rc;;
        esac;;
esac
__APP_AMD_WS_EMBED_EOF__
    cat > "$d/amd_ws.conf.sample" <<'__APP_AMD_WS_EMBED_EOF__'
; @@PLACEHOLDER amd_ws.conf.sample@@ - generated without this file; regenerate install.sh
__APP_AMD_WS_EMBED_EOF__
    chmod 755 "$d/ast-detect.sh"
}

is_placeholder() { grep -q '@@PLACEHOLDER' "$1" 2>/dev/null; }

build_module() {
    BUILD_DIR=$(mktemp -d "${TMPDIR:-/tmp}/app_amd_ws-build.XXXXXX")
    write_sources "$BUILD_DIR"
    if is_placeholder "$BUILD_DIR/app_amd_ws.c"; then
        die 5 "this installer was generated without app_amd_ws.c (development build) - use a release installer or run 'make installer' in a checkout that has the module source"
    fi
    local -a mk=(ASTERISK="${ASTERISK:-}" ASTVERSION="${ASTVERSION:-}" ASTBUILDSUM="${ASTBUILDSUM:-}"
                 ASTINCDIR="$ASTINCDIR" ASTMODDIR="${ASTMODDIR:-}" ASTNOCHECK="${ASTNOCHECK:-0}")
    if [ "$OPT_NO_DB" = 1 ]; then mk+=(MYSQL=0); else mk+=(MYSQL=auto); fi
    [ -z "${MYSQL_CFLAGS:-}" ] || mk+=(MYSQL_CFLAGS="$MYSQL_CFLAGS")
    [ -z "${MYSQL_LIBS:-}" ]   || mk+=(MYSQL_LIBS="$MYSQL_LIBS")
    log "building in $BUILD_DIR (headers: $ASTINCDIR)"
    run_logged make -C "$BUILD_DIR" "${mk[@]}" || die 5 "build failed - see $LOG_FILE"
    [ -f "$BUILD_DIR/$MODULE.so" ] || die 5 "build produced no $MODULE.so"
    log "built $BUILD_DIR/$MODULE.so ($(stat -c %s "$BUILD_DIR/$MODULE.so") bytes, AST_BUILDOPT_SUM $(strings -a "$BUILD_DIR/$MODULE.so" | grep -xE '[0-9a-f]{32}' | head -n1))"
}

# ----------------------------------------------------------------------------------------------
# module state in the running Asterisk ('asterisk -rx' always exits 0: parse the replies)
# ----------------------------------------------------------------------------------------------
# shellcheck disable=SC2086
ast_rx() { ad_run "$ASTERISK" ${ASTERISK_OPTS:-} -rx "$1" || true; }
module_row() { ast_rx "module show like $MODULE" | awk -v m="$MODULE.so" '$1==m'; }
module_loaded()  { [ -n "$(module_row)" ]; }
module_running() { case "$(module_row)" in *"Not Running"*) return 1;; *Running*) return 0;; *) return 1;; esac; }
module_usecount() { module_row | awk '{ if ($0 ~ /Not Running/) print $(NF-3); else print $(NF-2) }'; }
app_registered() { ast_rx "core show application $APP" | grep "Info about application '$APP'" >/dev/null; }

soft_unload() {   # rc 0 unloaded (or not loaded), rc 3 still in use after --wait seconds
    module_loaded || { log "$MODULE.so is not loaded in the running Asterisk"; return 0; }
    local waited=0 out
    while :; do
        out=$(ast_rx "module unload $MODULE.so")
        case $out in "Unloaded "*) log "unloaded old $MODULE.so"; return 0;; esac
        module_loaded || return 0
        if [ "$waited" -ge "$OPT_WAIT" ]; then
            warn "$MODULE.so is still in use after ${waited}s (use count $(module_usecount)); calls are NEVER hung up by this installer"
            return 3
        fi
        [ "$waited" = 0 ] && log "module in use by active calls (use count $(module_usecount)) - waiting up to ${OPT_WAIT}s for it to become idle"
        sleep 2; waited=$((waited+2))
    done
}

load_and_verify() {   # rc 0 loaded and AMD_WS registered
    local out
    out=$(ast_rx "module load $MODULE.so")
    case $out in "Loaded "*) ;; *) err "module load replied: ${out:-<nothing>}"; return 1;; esac
    module_running || { err "$MODULE.so is not Running after load"; return 1; }
    app_registered || { err "application $APP is not registered although the module loaded"; return 1; }
    return 0
}

old_code_resident() {   # the previous (deleted) file still mapped by the daemon?
    local pid; pid=$(ast_daemon_pid) || return 1
    grep -q "$MODULE\.so (deleted)" "/proc/$pid/maps" 2>/dev/null
}

# ----------------------------------------------------------------------------------------------
# install / uninstall
# ----------------------------------------------------------------------------------------------
install_module() {
    local dest="$ASTMODDIR/$MODULE.so" bak='' running=0 rc=0
    [ -n "${ASTMODDIR:-}" ] && [ -d "$ASTMODDIR" ] || die 1 "Asterisk module directory unknown - pass ASTMODDIR=/path in the environment"
    ast_running && running=1
    if [ -f "$dest" ]; then
        bak="$dest.bak.$(date +%Y%m%d%H%M%S)"; cp -p "$dest" "$bak"; log "backed up the previous module to $bak"
    fi
    install -m 755 "$BUILD_DIR/$MODULE.so" "$ASTMODDIR/.$MODULE.so.new"
    mv -f "$ASTMODDIR/.$MODULE.so.new" "$dest"
    log "installed $dest"
    if [ -f "$BUILD_DIR/amd_ws.conf.sample" ] && ! is_placeholder "$BUILD_DIR/amd_ws.conf.sample" && [ -d "$ETC_DIR" ]; then
        if install -m 644 "$BUILD_DIR/amd_ws.conf.sample" "$ETC_DIR/amd_ws.conf.sample" 2>/dev/null; then
            log "installed $ETC_DIR/amd_ws.conf.sample (copy to amd_ws.conf to change defaults; an existing amd_ws.conf is never touched)"
        else warn "could not write $ETC_DIR/amd_ws.conf.sample (permissions) - the sample is also in the repository"; fi
    fi
    if [ "$OPT_NO_LOAD" = 1 ]; then log "--no-load: not touching the running Asterisk; run: asterisk -rx 'module load $MODULE.so'"; return 0; fi
    if [ $running = 0 ]; then log "Asterisk is not running - the module will be loaded at the next start (autoload) or with: asterisk -rx 'module load $MODULE.so'"; return 0; fi
    soft_unload || rc=$?
    if [ $rc = 3 ]; then
        err "the new $dest is installed but the OLD module is still loaded and serving calls."
        err "Activate it when the dialer is idle with:"
        err "    asterisk${ASTERISK_OPTS:+ $ASTERISK_OPTS} -rx 'module unload $MODULE.so' && asterisk${ASTERISK_OPTS:+ $ASTERISK_OPTS} -rx 'module load $MODULE.so'"
        err "or at the next Asterisk restart. Nothing else is required."
        return 3
    fi
    if ! load_and_verify; then
        if [ -n "$bak" ]; then
            warn "restoring the previous module from $bak"
            cp -p "$bak" "$dest"; ast_rx "module load $MODULE.so" >/dev/null
            module_running && warn "previous module restored and running"
        fi
        die 5 "new module failed to load - see 'asterisk -rx \"core show settings\"' / /var/log/asterisk/messages and $LOG_FILE"
    fi
    if old_code_resident; then warn "the daemon still maps a deleted $MODULE.so - the old code may still be resident; a restart will clear it"; fi
    log "module loaded: $(module_row | sed 's/  */ /g')"
    log "application $APP registered: $(ast_rx "core show application $APP" | sed -n "s/.*-= Info about application '$APP' =-.*/ok/p" | head -n1)"
}

uninstall_module() {
    local d rc=0
    ast_detect_core
    if ast_running; then
        soft_unload || rc=$?
        [ $rc = 0 ] || warn "module still in use - removing the file anyway; it stays resident until Asterisk restarts"
    fi
    for d in ${ASTMODDIR:-} $AST_MODDIR_CANDS; do
        [ -f "$d/$MODULE.so" ] || continue
        rm -f "$d/$MODULE.so"; log "removed $d/$MODULE.so"
        if [ "$OPT_REMOVE_BACKUPS" = 1 ]; then rm -f "$d/$MODULE.so".bak.*; log "removed backups in $d"; else ls "$d/$MODULE.so".bak.* >/dev/null 2>&1 && log "backups kept: $d/$MODULE.so.bak.* (--remove-backups deletes them)"; fi
    done
    if [ -d "$CACHE_DIR" ]; then rm -rf "$CACHE_DIR"; log "removed header cache $CACHE_DIR"; fi
    log "kept: $ETC_DIR/amd_ws.conf*, installed packages, $LOG_FILE"
    return $rc
}

# ----------------------------------------------------------------------------------------------
# plan / dry run
# ----------------------------------------------------------------------------------------------
print_plan() {
    need_pkgs
    local deps="${NEED_PKGS[*]:-none}" db
    if [ "$OPT_NO_DB" = 1 ]; then db="disabled (--no-db)"; elif have_mysql_dev; then db="client dev files present"; else mysql_dev_candidates; db="would install one of: ${MYSQL_DEV_PKGS[*]:-none}"; fi
    cat <<EOF

app_amd_ws installer $AMD_WS_INSTALLER_VERSION - plan for this box
  distro / pkg manager : $DISTRO / $PKG
  build tools to add   : $deps
  MySQL client (DB)    : $db
  asterisk binary      : ${ASTERISK:-none} (${ASTERISK_SRC:-?}); daemon $(ast_running && echo running || echo "not running")
  asterisk version     : ${ASTVERSION:-unknown} (${ASTVERSION_SRC:-?})
  AST_BUILDOPT_SUM     : ${ASTBUILDSUM:-unknown} (${ASTBUILDSUM_SRC:-?})
  module directory     : ${ASTMODDIR:-unknown} (${ASTMODDIR_SRC:-?})
  headers              : ${HEADERS_HOW:-NONE FOUND}
  would install        : ${ASTMODDIR:-?}/$MODULE.so (backup of any existing file as .bak.<timestamp>), $ETC_DIR/amd_ws.conf.sample
  then                 : module unload (wait up to ${OPT_WAIT}s if busy, never hang up calls), module load, verify '$APP' registered
  log file             : $LOG_FILE
EOF
}

print_dialplan() {
    cat <<EOF

Dialplan example (extensions.conf), see README for all options:
    exten => 8370,1,AMD_WS(api.amdy.io,2700,\${CALLERID(name)},10000)
     same => n,GotoIf(\$["\${AMDCAUSE}"="NETERR" | "\${AMDCAUSE}"="INTERR"]?amd_fallback)
     same => n,GotoIf(\$["\${AMDSTATUS}"="HUMAN"]?human)
     ...
Settings: /etc/asterisk/amd_ws.conf (see amd_ws.conf.sample).  CLI: asterisk -rx 'amd_ws show settings'
EOF
}

# ----------------------------------------------------------------------------------------------
# main
# ----------------------------------------------------------------------------------------------
parse_args() {
    while [ $# -gt 0 ]; do
        case $1 in
            --uninstall) OPT_UNINSTALL=1;;
            --deps-only) OPT_DEPS_ONLY=1;;
            --build-only) OPT_BUILD_ONLY=1;;
            --no-db) OPT_NO_DB=1;;
            --no-load) OPT_NO_LOAD=1;;
            --headers) OPT_HEADERS=${2:?--headers needs a directory}; shift;;
            --asterisk-src) OPT_ASTERISK_SRC=${2:?--asterisk-src needs a directory}; shift;;
            --version) OPT_VERSION=${2:?--version needs a value}; shift;;
            --allow-configure) OPT_ALLOW_CONFIGURE=1;;
            --bundle-url) BUNDLE_URL=${2:?--bundle-url needs a URL}; shift;;
            --tarball-file) OPT_TARBALL_FILE=${2:?--tarball-file needs a file}; shift;;
            --wait) OPT_WAIT=${2:?--wait needs seconds}; shift;;
            --remove-backups) OPT_REMOVE_BACKUPS=1;;
            --dry-run) OPT_DRY_RUN=1;;
            --keep-build) OPT_KEEP_BUILD=1;;
            --output) OPT_OUTPUT=${2:?--output needs a path}; shift;;
            -y|--yes) OPT_YES=1;;
            -h|--help) usage; exit 0;;
            *) usage >&2; die 2 "unknown option: $1";;
        esac
        shift
    done
    case $OPT_WAIT in ''|*[!0-9]*) die 2 "--wait needs a whole number of seconds";; esac
    [ -z "$OPT_VERSION" ] || ASTVERSION=$OPT_VERSION
}

main() {
    parse_args "$@"
    init_log "$@"
    trap on_exit EXIT
    trap 'on_err $LINENO $?' ERR
    detect_distro
    log "app_amd_ws installer $AMD_WS_INSTALLER_VERSION (module commit $AMD_WS_SOURCE_COMMIT) on $DISTRO"

    if [ "$(id -u)" != 0 ] && [ "$OPT_DRY_RUN" = 0 ] && [ "$OPT_BUILD_ONLY" = 0 ]; then
        die 2 "run as root (sudo) - only --dry-run and --build-only work without root"
    fi
    if [ "$(id -u)" != 0 ]; then
        case $CACHE_DIR in /var/cache/*) CACHE_DIR="${TMPDIR:-/tmp}/app_amd_ws-cache-$(id -u)";; esac
    fi

    if [ "$OPT_UNINSTALL" = 1 ]; then uninstall_module; exit $?; fi

    ast_detect_core
    if [ "$OPT_DRY_RUN" = 1 ]; then
        resolve_headers || true
        print_plan; exit 0
    fi
    if [ "$OPT_DEPS_ONLY" = 1 ]; then install_deps || exit 6; log "dependencies done"; exit 0; fi

    if [ "$OPT_BUILD_ONLY" = 1 ] && [ "$(id -u)" != 0 ]; then
        need_pkgs; [ ${#NEED_PKGS[@]} -eq 0 ] || die 6 "missing build tools (install as root or run --deps-only): ${NEED_PKGS[*]}"
        have_mysql_dev || [ "$OPT_NO_DB" = 1 ] || { warn "no MySQL client dev files - building without the DB lookup"; OPT_NO_DB=1; }
    else
        install_deps || exit 6
    fi
    mkdir -p "$CACHE_DIR" 2>/dev/null || true

    if ! resolve_headers; then
        err "no Asterisk headers matching the running Asterisk ${ASTVERSION:-<unknown>} (sum ${ASTBUILDSUM:-<unknown>}) could be found or fetched."
        err "Next steps: --headers DIR | --asterisk-src DIR (configured+built tree) | --version VER | --allow-configure | --tarball-file FILE"
        err "            (details above; full log in $LOG_FILE)"
        exit 4
    fi
    log "headers: $HEADERS_HOW"
    print_plan
    if [ "$OPT_YES" = 0 ] && [ "$OPT_BUILD_ONLY" = 0 ] && [ -t 0 ]; then
        printf '[amd_ws] proceed? [Y/n] '; read -r ans; case $ans in n*|N*) log "aborted"; exit 1;; esac
    fi

    build_module
    if [ "$OPT_BUILD_ONLY" = 1 ]; then
        local out=${OPT_OUTPUT:-./$MODULE.so}
        cp -p "$BUILD_DIR/$MODULE.so" "$out"; log "--build-only: module written to $out"; exit 0
    fi
    local rc=0
    install_module || rc=$?
    [ $rc = 0 ] || exit $rc
    print_dialplan
    log "done. Log: $LOG_FILE"
}

if [ -z "${AMD_WS_INSTALL_LIB:-}" ]; then
    main "$@"
fi
