#!/bin/sh
# tools/check-embedded.sh - fail when install.sh is stale relative to the sources it embeds
#
#   tools/check-embedded.sh [install.sh]
#
# 1. extracts every embedded payload from install.sh and compares it byte for byte with the
#    repository file (app_amd_ws.c, Makefile, ast-detect.sh, amd_ws.conf.sample) and the inlined
#    ast-detect.sh library;
# 2. regenerates the installer with the commit/version/date recorded in its header and compares
#    the whole file, so a changed template (tools/install.sh.in) is caught too.
# Exit: 0 fresh | 1 stale (run 'make installer') | 2 install.sh carries a PLACEHOLDER (generated
# without app_amd_ws.c / amd_ws.conf.sample - must be regenerated before release) | 3 usage.

set -eu
LC_ALL=C; export LC_ALL
here=$(cd "$(dirname "$0")" && pwd); SRC=$(cd "$here/.." && pwd)
INST=${1:-$SRC/install.sh}
[ -f "$INST" ] || { echo "check-embedded: $INST not found" >&2; exit 3; }
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT INT TERM
EOFMARK=__APP_AMD_WS_EMBED_EOF__
rc=0

# payload N (1..4) = the N-th quoted heredoc in write_sources, in template order
extract() {   # $1 = index -> $TMP/payload.$1
    awk -v want="$1" -v mark="$EOFMARK" '
        $0 ~ "<<'"'"'" mark "'"'"'$" { n++; if (n == want) grab = 1; next }
        grab && $0 == mark { grab = 0; next }
        grab { print }' "$INST" > "$TMP/payload.$1"
}
i=1; args=""
for f in app_amd_ws.c Makefile ast-detect.sh amd_ws.conf.sample; do
    extract $i
    if [ ! -s "$TMP/payload.$i" ]; then echo "STALE   $f: no embedded copy found in $INST" >&2; rc=1
    elif grep -q '@@PLACEHOLDER' "$TMP/payload.$i"; then
        echo "PLACEHOLDER $f: install.sh was generated without this file - regenerate with 'make installer'" >&2; [ $rc = 0 ] && rc=2
        case $f in app_amd_ws.c) args="$args --module-c PLACEHOLDER";; amd_ws.conf.sample) args="$args --conf-sample PLACEHOLDER";; esac
    elif [ ! -f "$SRC/$f" ]; then echo "STALE   $f: embedded but missing from the repository" >&2; rc=1
    elif cmp -s "$TMP/payload.$i" "$SRC/$f"; then echo "fresh   $f"
    else echo "STALE   $f: embedded copy differs from $SRC/$f" >&2; rc=1; fi
    i=$((i+1))
done

# the inlined library must equal ast-detect.sh minus its shebang
awk '/^# embedded ast-detect.sh /{f=1; getline; next} /^# end of embedded ast-detect.sh/{f=0} f' "$INST" | sed '$d' > "$TMP/inline.sh"
sed '1{/^#!/d}' "$SRC/ast-detect.sh" > "$TMP/inline.want"
if cmp -s "$TMP/inline.sh" "$TMP/inline.want"; then echo "fresh   ast-detect.sh (inlined library)"
else echo "STALE   inlined ast-detect.sh differs from $SRC/ast-detect.sh" >&2; rc=1; fi

# whole-file comparison against a regeneration with the recorded provenance
commit=$(sed -n 's/^# Generated by tools\/gen-installer.sh from commit \([^ ]*\) on \([^ ]*\) (installer version \([^)]*\)).*/\1/p' "$INST" | head -n1)
date=$(sed -n 's/^# Generated by tools\/gen-installer.sh from commit \([^ ]*\) on \([^ ]*\) (installer version \([^)]*\)).*/\2/p' "$INST" | head -n1)
ver=$(sed -n 's/^# Generated by tools\/gen-installer.sh from commit \([^ ]*\) on \([^ ]*\) (installer version \([^)]*\)).*/\3/p' "$INST" | head -n1)
if [ -z "$commit" ]; then echo "STALE   no provenance header in $INST" >&2; rc=1
else
    # shellcheck disable=SC2086
    if sh "$here/gen-installer.sh" --src "$SRC" -o "$TMP/regen.sh" --commit "$commit" --version "$ver" --date "$date" $args 2>/dev/null \
        && cmp -s "$TMP/regen.sh" "$INST"; then echo "fresh   install.sh == regeneration from the template (commit $commit)"
    else echo "STALE   install.sh differs from a regeneration with tools/gen-installer.sh (template or sources changed)" >&2; [ $rc = 0 ] && rc=1; fi
fi
[ $rc = 0 ] && echo "check-embedded: OK" || echo "check-embedded: FAILED (rc $rc)" >&2
exit $rc
