#!/bin/sh
# tools/gen-installer.sh - generate the self-contained install.sh from the sources
#
#   tools/gen-installer.sh [-o install.sh] [--src DIR] [--module-c FILE|PLACEHOLDER]
#                          [--conf-sample FILE|PLACEHOLDER] [--makefile FILE] [--ast-detect FILE]
#                          [--commit REV] [--version VER] [--date DATE]
#
# The template tools/install.sh.in has three kinds of markers:
#   @@INLINE ast-detect.sh@@   the detection library, inlined as shell code (shebang dropped)
#   @@EMBED <file>@@           file content inside a quoted heredoc (written to the build dir)
#   @@GENERATED@@ @@COMMIT@@ @@VERSION@@   provenance
# A source that is missing (or named PLACEHOLDER) is embedded as a marked placeholder; the
# generated installer then refuses to build (app_amd_ws.c) or skips the file (conf sample), and
# tools/check-embedded.sh reports it, so a development installer can never ship by accident.
# 'make installer' calls this with the defaults; check-embedded.sh calls it with the recorded
# --commit/--version/--date to compare byte for byte.

set -eu
LC_ALL=C; export LC_ALL
die() { printf 'gen-installer: ERROR: %s\n' "$*" >&2; exit 1; }

here=$(cd "$(dirname "$0")" && pwd)
SRC=$(cd "$here/.." && pwd)
OUT="$SRC/install.sh"; TEMPLATE="$here/install.sh.in"
MODULE_C=''; CONF_SAMPLE=''; MAKEFILE=''; AST_DETECT=''; COMMIT=''; VERSION=''; DATE=''
while [ $# -gt 0 ]; do
    case $1 in
        -o|--out)      OUT=$2; shift 2;;
        --src)         SRC=$2; shift 2;;
        --module-c)    MODULE_C=$2; shift 2;;
        --conf-sample) CONF_SAMPLE=$2; shift 2;;
        --makefile)    MAKEFILE=$2; shift 2;;
        --ast-detect)  AST_DETECT=$2; shift 2;;
        --template)    TEMPLATE=$2; shift 2;;
        --commit)      COMMIT=$2; shift 2;;
        --version)     VERSION=$2; shift 2;;
        --date)        DATE=$2; shift 2;;
        -h|--help)     sed -n '2,18p' "$0"; exit 0;;
        *) die "unknown option $1";;
    esac
done
: "${MODULE_C:=$SRC/app_amd_ws.c}"
: "${CONF_SAMPLE:=$SRC/amd_ws.conf.sample}"
: "${MAKEFILE:=$SRC/Makefile}"
: "${AST_DETECT:=$SRC/ast-detect.sh}"
[ -f "$TEMPLATE" ]   || die "template $TEMPLATE not found"
[ -f "$MAKEFILE" ]   || die "Makefile $MAKEFILE not found"
[ -f "$AST_DETECT" ] || die "ast-detect.sh $AST_DETECT not found"

if [ -z "$COMMIT" ]; then
    if git -C "$SRC" rev-parse --short HEAD >/dev/null 2>&1; then
        COMMIT=$(git -C "$SRC" rev-parse --short HEAD)
        [ -z "$(git -C "$SRC" status --porcelain -- app_amd_ws.c Makefile ast-detect.sh amd_ws.conf.sample tools 2>/dev/null)" ] || COMMIT="$COMMIT-dirty"
    else
        COMMIT=unknown
    fi
fi
if [ -z "$VERSION" ]; then
    VERSION=$(git -C "$SRC" describe --tags --always 2>/dev/null || echo "$COMMIT")
fi
[ -n "$DATE" ] || DATE=$(date -u +%Y-%m-%d)

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT INT TERM

# resolve a source to a real file or a placeholder file
resolve() {   # $1 = logical name, $2 = path or PLACEHOLDER; prints the path to embed
    case $2 in
        PLACEHOLDER|'') ;;
        *) if [ -f "$2" ]; then printf '%s\n' "$2"; return 0; fi;;
    esac
    printf 'gen-installer: WARNING: %s not available - embedding a PLACEHOLDER (installer will refuse to build until regenerated)\n' "$1" >&2
    case $1 in
        app_amd_ws.c) printf '/* @@PLACEHOLDER app_amd_ws.c@@ - this installer was generated without the module source */\n#error "app_amd_ws.c placeholder: regenerate install.sh with tools/gen-installer.sh in a checkout that contains app_amd_ws.c"\n' > "$TMP/$1";;
        *)            printf '; @@PLACEHOLDER %s@@ - generated without this file; regenerate install.sh\n' "$1" > "$TMP/$1";;
    esac
    printf '%s\n' "$TMP/$1"
}
MODULE_C=$(resolve app_amd_ws.c "$MODULE_C")
CONF_SAMPLE=$(resolve amd_ws.conf.sample "$CONF_SAMPLE")

EOFMARK=__APP_AMD_WS_EMBED_EOF__
for f in "$MODULE_C" "$MAKEFILE" "$AST_DETECT" "$CONF_SAMPLE"; do
    ! grep -qxF "$EOFMARK" "$f" || die "$f contains the heredoc terminator $EOFMARK"
    # the heredoc always ends its last line with a newline; a source without one could never be
    # embedded byte for byte and check-embedded.sh would report it STALE for ever
    [ "$(tail -c 1 "$f" | od -An -c | tr -d ' ')" = '\n' ] || die "$f must end with a newline (the embedded copy would differ from the source)"
done

# the inlined library: drop the shebang, keep everything else verbatim
sed '1{/^#!/d}' "$AST_DETECT" > "$TMP/inline.sh"

GENERATED="Generated by tools/gen-installer.sh from commit $COMMIT on $DATE (installer version $VERSION). DO NOT EDIT: run 'make installer'."

awk -v modc="$MODULE_C" -v mk="$MAKEFILE" -v ad="$AST_DETECT" -v cs="$CONF_SAMPLE" -v inl="$TMP/inline.sh" \
    -v gen="$GENERATED" -v commit="$COMMIT" -v ver="$VERSION" '
function emit(path,   l) { while ((getline l < path) > 0) print l; close(path) }
/^@@EMBED app_amd_ws\.c@@$/       { emit(modc); next }
/^@@EMBED Makefile@@$/            { emit(mk); next }
/^@@EMBED ast-detect\.sh@@$/      { emit(ad); next }
/^@@EMBED amd_ws\.conf\.sample@@$/ { emit(cs); next }
/^@@INLINE ast-detect\.sh@@$/     { emit(inl); next }
{ gsub(/@@GENERATED@@/, gen); gsub(/@@COMMIT@@/, commit); gsub(/@@VERSION@@/, ver); print }
' "$TEMPLATE" > "$TMP/install.sh"

grep -q '@@EMBED\|@@INLINE\|@@GENERATED@@\|@@COMMIT@@\|@@VERSION@@' "$TMP/install.sh" && die "unreplaced marker left in the output"
bash -n "$TMP/install.sh" || die "generated installer does not parse"
cp "$TMP/install.sh" "$OUT" && chmod 755 "$OUT"
printf 'gen-installer: wrote %s (%s bytes, commit %s, version %s)\n' "$OUT" "$(wc -c < "$OUT")" "$COMMIT" "$VERSION" >&2
